//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ape++.rc
//
#define IDD_FIND                        104
#define IDD_GOTO                        105
#define IDI_APE                         107
#define IDI_APE_SM                      108
#define IDC_MENU                        109
#define IDC_ACCEL                       109
#define IDC_POPUP_SCI                   129
#define IDC_FIND_SEARCHTEXT             150
#define IDC_FIND_REPLACEON              151
#define IDC_FIND_FILES                  152
#define IDC_FIND_FILE_DIR               153
#define IDC_FIND_MATCHWORDS             154
#define IDC_FIND_MATCHCASE              155
#define IDC_FIND_MODE                   156
#define IDC_FIND_FILE_SUBDIRS           157
#define IDC_FIND_FILE_OUT2              159
#define IDC_FIND_FILE_BACKUP            160
#define IDC_FIND_UP                     161
#define IDC_FIND_DOWN                   162
#define IDC_FIND_REPLACESEL             163
#define IDC_FIND_REPLACEFILE            164
#define IDC_FIND_REPLACE_BTN            165
#define IDC_FIND_REPLACEALL_BTN         166
#define IDC_FIND_BTN                    167
#define IDC_FIND_SEARCH                 168
#define IDC_FINDALL_BTN                 171
#define IDC_FIND_REPLACE                172
#define IDC_FIND_REPLACETEXT            173
#define IDC_FIND_FILE_TYPES             174
#define IDC_FIND_FILE_BRW               175
#define IDC_FIND_OPTION_FIND            178
#define IDC_FIND_FILE_REPLACE           179
#define IDC_POPUP_TAB                   200
#define IDR_TOOLBAR_SEARCH              202
#define IDR_TOOLBAR_WND                 203
#define IDR_TOOLBAR_FOLD                204
#define IDR_TOOLBAR_MISC                205
#define IDD_INTEGR                      205
#define IDD_ABOUT                       206
#define IDC_STATIC                      206
#define IDC_STATIC2                     207
#define IDR_TOOLBAR                     207
#define IDI_WINCMD                      207
#define IDI_NOTEPAD                     208
#define IDC_GOTO_NUMBER                 210
#define IDC_GOTO_POS                    212
#define IDC_GOTO_LINE                   213
#define IDC_GOTO_CUR                    214
#define IDC_GOTO_LAST                   215
#define IDC_POPUP_STYLE                 218
#define IDC_POPUP_ENCODING              219
#define IDC_POPUP_OVR                   220
#define IDC_POPUP_EOL                   221
#define IDC_POPUP_FUNC_COMBO            222
#define IDB_CLOSEBTN                    223
#define IDD_COLORS                      224
#define IDD_OPTIONS                     225
#define IDD_SORT                        226
#define IDD_TABS                        227
#define IDD_INDICATORS                  228
#define IDC_POPUP_GOTO                  229
#define IDD_CHECK_LIST                  230
#define IDC_GOTO_CUR_LBL                1001
#define IDC_GOTO_LAST_LBL               1002
#define IDC_BTN_CM_REG                  1003
#define IDC_BTN_CM_UNREG                1004
#define IDC_BTN_NOTE_SET                1005
#define IDC_BTN_NOTE_REMOVE             1006
#define IDC_BTN_WC_SET                  1007
#define IDC_BTN_WC_CLEAR                1008
#define IDC_EDITORHL_TREE               1010
#define IDC_EDITORHL_BOLD               1011
#define IDC_EDITORHL_ITALIC             1012
#define IDC_EDITORHL_UNDERLINE          1013
#define IDC_EDITORHL_EOL                1014
#define IDC_EDITORHL_SIZE_C             1015
#define IDC_EDITORHL_SPINSIZE           1016
#define IDC_EDITORHL_FONT_C             1017
#define IDC_EDITORHL_FORE_C             1018
#define IDC_EDITORHL_FORE               1019
#define IDC_EDITORHL_BACK_C             1020
#define IDC_EDITORHL_BACK               1021
#define IDC_EDITORHL_SAMPLE             1022
#define IDC_EDITORHL_SIZE               1023
#define IDC_EDITORHL_FONT               1024
#define IDC_EDITORHL_CLRFORE            1025
#define IDC_EDITORHL_CLRBACK            1026
#define IDC_OPT_CHK_EXT_MODIFY          1030
#define IDC_OPT_CHK_ONE_INSTANCE        1031
#define IDC_OPT_CHK_AUTOINDENT          1032
#define IDC_OPT_CHK_SAVEONDEACTIVATE    1033
#define IDC_OPT_CHK_STRIPTRAILSPACE     1034
#define IDC_OPT_ED_TABSIZE              1035
#define IDC_OPT_TABSIZE                 1035
#define IDC_SORT_ASC                    1036
#define IDC_SORT_DESC                   1037
#define IDC_SORT_IGNORECASE             1038
#define IDC_SORT_TRIM                   1039
#define IDC_OPT_TABS_CLOSEBTN           1040
#define IDC_OPT_TABS_DRAGNDROP          1041
#define IDC_LIST                        1042
#define ID_EDIT_UNDO                    32771
#define ID_EDIT_REDO                    32772
#define ID_EDIT_CUT                     32773
#define ID_EDIT_COPY                    32774
#define ID_EDIT_PASTE                   32775
#define ID_EDIT_DELETE                  32776
#define ID_EDIT_SELECTALL               32777
#define ID_EDIT_READONLY                32778
#define ID_EDIT_OPENFILE                32780
#define ID_EDIT_UPPERCASE               32781
#define ID_EDIT_LOWERCASE               32782
#define ID_EDIT_VP                      32783
#define ID_FILE_NEW                     32790
#define ID_FILE_OPEN                    32791
#define ID_FILE_SAVE                    32792
#define ID_FILE_SAVEAS                  32793
#define ID_FILE_CLOSE                   32794
#define ID_FILE_SAVEALL                 32795
#define ID_FILE_EXIT                    32796
#define ID_TAB_SELECT                   32800
#define ID_TAB_ALTERNATE                32801
#define ID_TAB_SHELLMENU                32802
#define ID_TAB_SETCURDIR                32803
#define ID_WINDOW_NEXT                  32810
#define ID_WINDOW_PREV                  32811
#define ID_WINDOW_CLOSE                 32812
#define ID_WINDOW_CLOSE_GROUP           32813
#define ID_WINDOW_CLOSE_EXCEPT          32814
#define ID_WINDOW_CLOSE_ALL             32815
#define ID_SEARCH_FIND                  32820
#define ID_SEARCH_REPLACE               32821
#define ID_SEARCH_FINDFILE              32822
#define ID_SEARCH_REPLACEFILE           32823
#define ID_SEARCH_FINDNEXT              32824
#define ID_SEARCH_FINDPREV              32825
#define ID_SEARCH_MATCHBRACE            32826
#define ID_SEARCH_GOTO                  32827
#define ID_HELP_ABOUT                   32830
#define ID_VIEW_ALWAYSONTOP             32840
#define ID_VIEW_FULLSCREEN              32841
#define ID_VIEW_WS_NONE                 32842
#define ID_VIEW_WS_PART                 32843
#define ID_VIEW_WS_ALL                  32844
#define ID_VIEW_BRACE                   32845
#define ID_VIEW_INDENT                  32846
#define ID_VIEW_EOL                     32847
#define ID_VIEW_NUMS                    32848
#define ID_VIEW_LINEHL                  32849
#define ID_EDIT_AUTOC                   32858
#define ID_EDIT_FORMATINDENT            32876
#define ID_FOLDING_TOGGLE               32880
#define ID_FOLDING_COLLAPSE             32881
#define ID_FOLDING_EXPAND               32882
#define ID_FOLDING_TOGGLEALL            32883
#define ID_FOLDING_COLLAPSEALL          32884
#define ID_FOLDING_EXPANDALL            32885
#define ID_NONE                         32886
#define ID_FILE_EXPORT2HTML             32890
#define ID_EDIT_COPYASHTML              32891
#define ID_SEARCH_MATCHFOLD             32892
#define ID_EDIT_JUMP                    32893
#define ID_OPTIONS_INTEGR               32933
#define IDC_LBL_WC                      32934
#define ID_OPTIONS_LANGUAGES            32935
#define ID_LANG_FIRST                   32940
#define ID_LANG_LAST                    32970
#define ID_EDIT_CALLTIP                 32971
#define ID_ENCODING_ANSI                32972
#define ID_ENCODING_UTF8                32973
#define ID_ENCODING_UTF8_NO_BOM         32974
#define ID_ABOUT_LABEL                  32975
#define ID_ABOUT_ICO                    32976
#define ID_TAB_PIN                      33100
#define ID_EDIT_STYLE1                  33101
#define ID_EDIT_STYLE2                  33102
#define ID_EDIT_STYLE3                  33103
#define ID_EDIT_STYLE4                  33104
#define ID_EDIT_STYLE5                  33105
#define ID_EDIT_STYLE6                  33106
#define ID_EDIT_STYLE7                  33107
#define ID_EDIT_CLEAR_STYLE1            33111
#define ID_EDIT_CLEAR_STYLE2            33112
#define ID_EDIT_CLEAR_STYLE3            33113
#define ID_EDIT_CLEAR_STYLE4            33114
#define ID_EDIT_CLEAR_STYLE5            33115
#define ID_EDIT_CLEAR_STYLE6            33116
#define ID_EDIT_CLEAR_STYLE7            33117
#define ID_EDIT_CLEAR_STYLE_ALL         33120
#define ID_EDIT_RESTYLEALL              33121
#define ID_EDIT_STYLES                  33122
#define ID_EOL_CRLF                     33130
#define ID_EOL_CR                       33131
#define ID_EOL_LF                       33132
#define ID_VIEW_ZOOMIN                  33142
#define ID_VIEW_ZOOMOUT                 33143
#define ID_VIEW_ZOOMRESET               33144
#define ID_OVR                          33145
#define ID_INS                          33146
#define ID_SORT_BY_NAME                 33150
#define ID_SORT_BY_LINE                 33151
#define ID_MRU_CLEAR                    33200
#define ID_MRU_OPENALL                  33201
#define ID_MRU_FIRST                    33202
#define ID_MRU_LAST                     33299
#define ID_PIN_CLEAR                    33300
#define ID_PIN_OPENALL                  33301
#define ID_PIN_FIRST                    33302
#define ID_PIN_LAST                     33399
#define ID_LEXER_FIRST                  33400
#define ID_LEXER_LAST                   33599
#define ID_SEARCH_CLEARINDIC            33601
#define ID_OPTIONS_COLORS               33602
#define ID_OPTIONS_SETTINGS             33603
#define ID_OPTIONS_OPTIONS              33604
#define ID_EDIT_SORT                    33606
#define ID_TAB_MOVE2NEWAPE              33607
#define ID_TAB_OPEN2NEWAPE              33608
#define ID_VIEW_XMLTAGS                 33609
#define ID_EDIT_INCLUDES                33610
#define ID_EDIT_COPYASHEX               33611
#define ID_VIEW_WRAPLINES               33612
#define ID_ENCODING_UTF16BE             33616
#define ID_ENCODING_UTF16LE             33617
#define ID_TAB_SORT_BYNAME              33625
#define ID_TAB_SORT_BYEXT               33627
#define ID_TAB_SORT_BYPATH              33628
#define ID_ENCODING_LATIN1              33629
#define ID_ENCODING_LATIN2              33630
#define ID_ENCODING_LATIN3              33631
#define ID_ENCODING_ANSI_CYR            33645
#define ID_VIEW_TOKEN                   33632
#define ID_OPTIONS_NOTONEINSTANCE       33633
#define ID_WINDOW_CLOSE_TORIGHT         33634
#define ID_EDIT_FORMATXML               33635
#define ID_OPTIONS_INDICATORS           33636
#define ID_EDIT_STRIPTRAILINGSPACES     33637
#define ID_TAB_OPENFOLDER               33638
#define ID_GOTO_POSITION                33639
#define ID_GOTO_LINE                    33640
#define ID_FOLDING_TOGGLECHILD          33641
#define ID_FOLDING_COLLAPSECHILD        33642
#define ID_FOLDING_EXPANDCHILD          33643
#define ID_EDIT_OPENDIR                 33644
#define ID_EDIT_WRAPLINES               33646
#define ID_TAB_CHECKED                  33647

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        231
#define _APS_NEXT_COMMAND_VALUE         33648
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
