#define yyFlexLexer cpp_FlexLexer
#define yywrap cpp_wrap

#line 5 "C:\\work\\ape++\\src\\lexers\\LexerCPP.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: k:\\backup\\cvsroot/ape/lexer/Lexer.skl,v 1.1 2000/11/15 13:38:44 Basil_Burdo Exp $
 */
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#undef	yywrap

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
    #ifndef __cplusplus
        #define __cplusplus
    #endif
#endif


#ifdef __cplusplus
    #include <stdlib.h>
//  #include <unistd.h>
    class istream;

    /* Use prototypes in function declarations. */
    #define YY_USE_PROTOS
    /* The "const" storage-class-modifier is valid. */
    #define YY_USE_CONST
#else   /* ! __cplusplus */
    #if __STDC__
        #define YY_USE_PROTOS
        #define YY_USE_CONST
    #endif  /* __STDC__ */
#endif  /* ! __cplusplus */

#ifdef YY_USE_CONST
    #define yyconst const
#else
    #define yyconst
#endif

#ifdef YY_USE_PROTOS
    #define YY_PROTO(proto) proto
#else
    #define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.*/
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.*/
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.*/
#define YY_START			((yy_start - 1) / 2)
#define YYSTATE				YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *  if ( condition_holds )
 *      yyless( 5 );
 *  else
 *      do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        *yy_cp = yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).*/
typedef unsigned int yy_size_t;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
    { \
        if ( ! yy_current_buffer ) \
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
        yy_current_buffer->yy_is_interactive = is_interactive; \
    }

#define yy_set_bol(at_bol) \
    { \
        if ( ! yy_current_buffer ) \
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
        yy_current_buffer->yy_at_bol = at_bol; \
    }

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

/************************************************************************/
/* start of yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init  */

#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int CSciLexer<yyFlexLexer>::yylex()
/* end of yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init    */
/************************************************************************/


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
    yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
    yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yy_c_buf_p = yy_cp;

/*********************************************************************************/
/* start of data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
static yyconst short int yy_acclist[284] =
    {   0,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   42,   47,   42,   47,   51,   49,   50,   47,
       49,   50,   48,   50,   49,   50,   25,   49,   50,    3,
       49,   50,    4,   49,   50,   19,   25,   49,   50,   20,
       25,   49,   50,   25,   49,   50,   14,   16,   49,   50,
       13,   16,   49,   50,   49,   50,   12,   46,   49,   50,
       21,   25,   49,   50,   22,   25,   49,   50,   12,   46,
       49,   50,   17,   25,   49,   50,   18,   25,   49,   50,
       26,   49,   50,   47,   49,   50,   49,   50,   12,   46,
       49,   50,   12,   46,   49,   50,   49,   50,   46,   49,

       50,   27,   48,   50,   49,   50,   37,   48,   50,   49,
       50,   30,   49,   50,   49,   50,   31,   49,   50,   49,
       50,   41,   48,   50,   49,   50,   49,   50,   46,   49,
       50,   45,   49,   50,   45,   47,   49,   50,   43,   48,
       50,   45,   49,   50,   42,   45,   47,   49,   50,   44,
       45,   49,   50,   42,   45,   49,   50,   42,   45,   46,
       49,   50,   45,   46,   49,   50,   47,   48,    2,    1,
       14,   16,   16,   13,   16,   11,   12,   46,   12,   46,
       26,   47,    5,   12,   46,   12,   46,   28,   46,   27,
       48,   37,   48,   36,   29,   36,   32,   36,   34,   36,

       36,   33,   36,   41,   48,   40,   46,   43,   48,   42,
       47,   42,   42,   46,   16,   16,   15,   12,   46,   12,
       46,   12,   46,16394,   34,   46,   46,   23,   24,   15,
       12,   46,16394,   12,   46, 8202,   12,   46,   34,   35,
       46,   46,    6,   12,   46,16393,    8,   12,   46,   46,
       46,16393,    8, 8201,   12,   46,   46,   46,    7,   12,
       46,   46,   46,    7,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   39,
       46,   38,   46
    } ;

static yyconst short int yy_accept[172] =
    {   0,
        1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       11,   12,   13,   15,   17,   18,   20,   23,   25,   27,
       30,   33,   36,   40,   44,   47,   51,   55,   57,   61,
       65,   69,   73,   77,   81,   84,   87,   89,   93,   97,
       99,  102,  105,  107,  110,  112,  115,  117,  120,  122,
      125,  127,  129,  132,  135,  139,  142,  145,  150,  154,
      158,  163,  167,  168,  169,  170,  171,  171,  173,  174,
      174,  174,  176,  177,  179,  181,  182,  183,  183,  183,
      183,  183,  184,  186,  188,  189,  190,  192,  194,  195,
      196,  197,  199,  201,  202,  204,  206,  207,  207,  208,

      210,  212,  213,  215,  215,  215,  216,  216,  217,  218,
      220,  220,  220,  222,  225,  226,  226,  227,  228,  229,
      230,  231,  233,  233,  234,  236,  237,  237,  239,  240,
      241,  242,  243,  243,  244,  244,  244,  247,  250,  251,
      252,  253,  254,  255,  255,  257,  258,  259,  259,  262,
      263,  264,  265,  266,  267,  268,  269,  270,  271,  272,
      273,  274,  275,  276,  277,  278,  279,  280,  282,  284,
      284
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    6,    6,    6,    9,   10,
       11,   12,   13,    6,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,    6,    6,    6,
        6,    6,   20,   21,   22,   23,   22,   24,   25,   22,
       26,   27,   28,   27,   27,   27,   27,   29,   27,   27,
       27,   27,   27,   27,   30,   27,   27,   31,   27,   27,
       32,   33,   34,    1,   35,    6,   36,   37,   38,   39,

       40,   37,   41,   42,   43,   42,   42,   42,   44,   45,
       46,   47,   42,   48,   49,   50,   51,   52,   42,   53,
       42,   42,   54,    6,   55,    6,    1,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,

       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56
    } ;

static yyconst int yy_meta[57] =
    {   0,
        1,    2,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    1,    4,    4,    4,    1,
        1,    5,    5,    5,    5,    6,    6,    6,    6,    6,
        6,    1,    1,    1,    7,    8,    8,    8,    8,    8,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    1,    1,    1
    } ;

static yyconst short int yy_base[182] =
    {   0,
        0,   55,   80,    0,   55,   58,  134,  136,  141,  148,
      151,  158,  207,    0,  415,  531,   63,  531,  410,  531,
      531,  531,  531,  531,   57,  249,  158,    0,    0,  531,
      531,  361,  531,  531,  355,  163,   69,  385,  380,  392,
        0,  531,  404,  531,  397,  531,  300,  531,  351,  531,
      395,   72,  345,  531,  154,  531,  390,  177,  531,  390,
      400,    0,  185,  531,  531,  138,  177,  254,  266,  279,
        0,  304,    0,    0,  348,  334,  303,  197,  364,  357,
      199,  201,  359,  359,  531,    0,  531,  531,  531,  531,
      378,  531,  258,    0,  531,  531,  531,  377,  241,  531,

      308,  377,    0,  323,  321,  321,  282,  324,  134,  333,
      338,  335,  329,  321,  297,    0,  307,  302,  531,  531,
      531,  325,  319,  359,  305,  531,  329,  419,  531,  531,
      262,  260,  368,  531,  261,    0,  362,    0,  253,  242,
      371,    0,  531,  279,  433,  234,  234,    0,    0,  229,
      158,    0,  150,  154,  145,  130,  124,  126,  118,  108,
      106,   99,   36,   31,   26,   21,   19,    0,    0,  531,
      464,  470,  478,  484,  493,  501,  506,  511,  516,  520,
      523
    } ;

static yyconst short int yy_def[182] =
    {   0,
      170,    1,  170,    3,    3,    3,    3,    3,    3,    3,
        3,    3,  170,   13,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  171,  172,  170,
      170,  172,  170,  170,  170,  170,  173,  172,  172,  170,
      174,  170,  170,  170,  170,  170,  175,  170,  175,  170,
      170,  170,  174,  170,  170,  170,  170,  176,  170,  176,
      174,  174,  170,  170,  170,  170,  170,  170,  170,  170,
      177,  170,  171,  172,  172,  170,  170,  173,  170,  170,
      173,  173,  172,  172,  170,  174,  170,  170,  170,  170,
      170,  170,  170,  178,  170,  170,  170,  170,  174,  170,

      176,  176,   61,  170,  170,  170,  170,  170,  177,  172,
      170,  170,  172,  172,  170,  179,  174,  174,  170,  170,
      170,  172,  170,  170,  172,  170,  170,  172,  170,  170,
      174,  174,  170,  170,  170,  180,  172,  128,  174,  174,
      170,  180,  170,  170,  128,  174,  174,  181,  145,  174,
      174,  181,  174,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  174,  174,    0,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170
    } ;

static yyconst short int yy_nxt[588] =
    {   0,
       16,   17,   18,   19,   17,   20,   21,   16,   22,   23,
       24,   20,   20,   20,   20,   25,   26,   27,   27,   20,
       28,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   30,   20,   31,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       32,   29,   29,   33,   34,   35,   36,   42,   43,   36,
       42,   43,   37,  169,   63,  168,   16,   63,   65,   16,
       81,  167,   66,   81,   97,   98,  166,   38,  165,   39,
       16,   17,   18,   19,   17,   16,   16,   16,   16,   16,
       16,   40,   16,   16,   16,   16,   16,   16,   16,   16,

       16,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   16,   16,   16,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   16,   16,   16,   44,   45,   44,   45,
       46,  164,   46,   44,   45,   16,  163,   16,  162,   48,
       44,   45,   16,   50,   51,   63,   48,  161,   63,   16,
       50,   51,   16,  121,   77,  160,   47,   77,   47,   16,
       78,  159,   67,   49,   72,   72,   72,  158,   63,  157,
       49,  101,   70,   52,  121,   79,   63,   80,  156,   63,
       52,  104,  105,  106,  106,  106,  155,   70,   81,   53,

       81,   81,  170,   81,  154,  170,   53,   54,   55,   56,
       57,   58,   54,   54,   54,   54,   54,   59,   54,   54,
       60,   54,   54,   60,   60,   60,   54,   54,   61,   61,
       61,   61,   62,   62,   62,   62,   62,   62,   54,   54,
       54,   62,   61,   61,   61,   61,   61,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       54,   54,   54,   67,  153,   68,   68,   69,   67,  151,
       68,   68,   69,   70,  115,  115,  117,  150,   70,   71,
       67,  143,   69,   69,   69,  147,  118,  146,   70,  141,
       70,  107,  107,   70,  140,  108,  108,  108,  108,  108,

      108,   71,   90,   91,   77,   70,   92,   77,   92,   63,
       78,  139,  101,  129,  129,   92,   93,   93,   67,   92,
       72,   72,   72,  126,  127,   79,  133,   80,   70,  133,
       94,  126,   92,  137,  134,   92,   92,  106,  106,  106,
      108,  108,  108,   70,   92,   70,  135,   92,  132,   92,
       95,   92,   94,  170,  131,  128,  125,   92,  124,   92,
       70,  126,  127,  123,  143,  144,   92,   93,   93,  133,
       92,  122,  133,  143,  144,  120,  119,  134,  170,   97,
       90,   94,  114,   92,  113,  112,   92,   92,  111,   76,
      110,  170,  100,  136,   99,   92,  145,   96,   92,   88,

       92,   95,   92,   94,  102,  148,   87,   85,   84,   83,
       76,   75,   64,  102,  170,  170,  103,  103,  103,  170,
      170,  103,  103,  103,  103,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  103,  103,  103,  103,  103,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      170,  170,  170,  138,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  170,  170,  170,  149,   73,   73,
      170,   73,   73,   74,   74,   74,   74,   74,   74,   82,
      170,  170,  170,  170,  170,   82,   82,   86,   86,   86,
       86,   86,   86,   89,   89,   89,   89,   89,   89,   89,

       89,   89,  102,  102,  102,  102,  170,  170,  102,  109,
      109,  170,  170,  109,  116,  116,  170,  170,  116,  130,
      130,  170,  170,  130,  142,  142,  142,  152,  152,  152,
       15,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170
    } ;

static yyconst short int yy_chk[588] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    5,    5,    2,
        6,    6,    2,  167,   17,  166,    5,   17,   25,    6,
       37,  165,   25,   37,   52,   52,  164,    2,  163,    2,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    7,    7,    8,    8,
        7,  162,    8,    9,    9,    7,  161,    8,  160,    9,
       10,   10,    9,   11,   11,   55,   10,  159,   55,   10,
       12,   12,   11,  109,   36,  158,    7,   36,    8,   12,
       36,  157,   27,    9,   27,   27,   27,  156,   58,  155,
       10,   58,   27,   11,  109,   36,   63,   36,  154,   63,
       12,   66,   66,   67,   67,   67,  153,   27,   78,   11,

       81,   78,   82,   81,  151,   82,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   26,  150,   26,   26,   26,   68,  147,
       68,   68,   68,   26,   93,   93,   99,  146,   68,   26,
       69,  144,   69,   69,   69,  140,   99,  139,   26,  135,
       69,   70,   70,   68,  132,   70,   70,   70,  107,  107,

      107,   26,   47,   47,   77,   69,   47,   77,   47,  101,
       77,  131,  101,  115,  115,   47,   47,   47,   72,   47,
       72,   72,   72,  114,  114,   77,  122,   77,   72,  122,
       47,  127,   47,  125,  122,   47,   47,  106,  106,  106,
      108,  108,  108,   72,   47,  106,  123,   47,  118,   47,
       47,   47,   47,   49,  117,  114,  113,   49,  112,   49,
      106,  124,  124,  111,  137,  137,   49,   49,   49,  133,
       49,  110,  133,  141,  141,  105,  104,  133,  102,   98,
       91,   49,   84,   49,   83,   80,   49,   49,   79,   76,
       75,   60,   57,  124,   53,   49,  137,   51,   49,   45,

       49,   49,   49,   49,   61,  141,   43,   40,   39,   38,
       35,   32,   19,   61,   15,    0,   61,   61,   61,    0,
        0,   61,   61,   61,   61,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   61,   61,   61,   61,   61,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
        0,    0,    0,  128,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,    0,    0,    0,  145,  171,  171,
        0,  171,  171,  172,  172,  172,  172,  172,  172,  173,
        0,    0,    0,    0,    0,  173,  173,  174,  174,  174,
      174,  174,  174,  175,  175,  175,  175,  175,  175,  175,

      175,  175,  176,  176,  176,  176,    0,    0,  176,  177,
      177,    0,    0,  177,  178,  178,    0,    0,  178,  179,
      179,    0,    0,  179,  180,  180,  180,  181,  181,  181,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170
    } ;

#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
#define INITIAL 0
#line 2 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
#include "LexBase.h"
#define COMMENT 1
#define SLCOMMENT 2
#define STRING 3
#define CHAR 4
#define PREPROCESSOR 5
#define UID 6

// without - "'	esc []-\/   !
#line 24 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"

bool isCppKeyword( const char* text, int lang ) 
{	
	switch( lang ) {
		case 1: { static CKeywords kw("TXT_CPP_KW"); return kw.is(text); }
		case 2: { static CKeywords kw("TXT_C_KW"); return kw.is(text); }
		case 3: { static CKeywords kw("TXT_CS_KW"); return kw.is(text); }
		case 4: { static CKeywords kw("TXT_IDL_KW"); return kw.is(text); }
		case 5: { static CKeywords kw("TXT_RC_KW"); return kw.is(text); }
		case 6: { static CKeywords kw("TXT_JAVA_KW"); return kw.is(text); }
		case 7: { static CKeywords kw("TXT_PROTO_KW"); return kw.is(text); }
	}
	return false;
}

#define STYLE_TEXT			0
#define STYLE_KW			1
#define STYLE_COMMENT		2
#define STYLE_SYMBOL		3
#define STYLE_STRING		4
#define STYLE_CHAR			5
#define STYLE_NUMBER		6
#define STYLE_PREP			7
#define STYLE_UNQ			8
#define STYLE_UID			9
#define STYLE_AT			10

#line 543 "C:\\work\\ape++\\src\\lexers\\LexerCPP.cpp"
/* end of data tables for the DFA and the user's section 1 definitions go here   */
/*********************************************************************************/


#ifndef yytext_ptr
    static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
    static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
    static int yy_start_stack_ptr = 0;
    static int yy_start_stack_depth = 0;
    static int *yy_start_stack = 0;
    #ifndef YY_NO_PUSH_STATE
        static void yy_push_state YY_PROTO(( int new_state ));
    #endif
    #ifndef YY_NO_POP_STATE
        static void yy_pop_state YY_PROTO(( void ));
    #endif
    #ifndef YY_NO_TOP_STATE
        static int yy_top_state YY_PROTO(( void ));
    #endif
#else
    #define YY_NO_PUSH_STATE    1
    #define YY_NO_POP_STATE     1
    #define YY_NO_TOP_STATE     1
#endif

#ifdef YY_MALLOC_DECL
    YY_MALLOC_DECL
#else
    #if __STDC__
        #ifndef __cplusplus
            #include <stdlib.h>
        #endif
    #else
        /* Just try to get by without declaring the routines.  This will fail
         * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
         * or sizeof(void*) != sizeof(int).
         */
    #endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
    #define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
    #define ECHO LexerOutput( yytext, yyleng )
#endif /* !ECHO */

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
    #define YY_INPUT(buf,result,max_size) \
        if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
            YY_FATAL_ERROR( "input in flex scanner failed" );
#endif /* !YY_INPUT */

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.*/
#ifndef yyterminate
    #define yyterminate() return YY_NULL
#endif /* !yyterminate */

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
    #define YY_START_STACK_INCR 25
#endif /* !YY_START_STACK_INCR */

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
    #define YY_FATAL_ERROR(msg) LexerError( msg )
#endif /* !YY_FATAL_ERROR */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
    #define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.*/
#ifndef YY_USER_ACTION
    #define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
    #define YY_BREAK    break;
#endif

/************************************************************************/
/* start of YY_RULE_SETUP definition                                    */
#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION
/* end of YY_RULE_SETUP definition                                      */
/************************************************************************/

YY_DECL
{
    register yy_state_type yy_current_state;
    register char *yy_cp, *yy_bp;
    register int yy_act;

/************************************************************************/
/* start of user's declarations                                         */
#line 53 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"

 /*************************************************************************************/

#line 670 "C:\\work\\ape++\\src\\lexers\\LexerCPP.cpp"
/* end of user's declarations                                           */
/************************************************************************/

    if( yy_init ) {
        yy_init = 0;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif /* YY_USER_INIT */

        if( !yy_start )
            yy_start = 1;   /* first start state */

        if( !yyin )
            yyin = &cin;

        if( !yyout )
            yyout = &cout;

        if( !yy_current_buffer )
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

        yy_load_buffer_state();
    }

    while( 1 )      /* loops until end-of-file is reached */
    {
/************************************************************************/
/* start of yymore()-related code                                       */
/* end of yymore()-related code                                         */
/************************************************************************/
        
        yy_cp = yy_c_buf_p;

        *yy_cp = yy_hold_char; /* Support of yytext. */

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run. */
        yy_bp = yy_cp;

/************************************************************************/
/* start of code to set up and find next match                          */
		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 171 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 531 );
/* end of code to set up and find next match                            */
/************************************************************************/

yy_find_action:

/************************************************************************/
/* start of code to find the action number                              */
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}
/* end of code to find the action number                                */
/************************************************************************/

        YY_DO_BEFORE_ACTION;

/************************************************************************/
/* start of code for yylineno update                                    */
/* end if code for yylineno update                                      */
/************************************************************************/

do_action:  /* This label is used only to access EOF actions. */

/************************************************************************/
/* start of debug code                                                  */
/* end of debug code                                                    */
/************************************************************************/
        switch ( yy_act ) { /* beginning of action switch */
/************************************************************************/
/* start of actions code                                                */

case 1:
YY_RULE_SETUP
#line 57 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
BEGIN(SLCOMMENT); SetStyle();
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
BEGIN(COMMENT);   SetStyle(); levelIncrease();
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 59 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
BEGIN(STRING);	  SetStyle();
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
BEGIN(CHAR);	  SetStyle();
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 62 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
{ //preprocessor
								char* pText;
								for( pText=yytext; *pText!='#'; pText++ );
								SetStyle( MatchStart(), MatchStart()+(pText-yytext), STYLE_TEXT );
								SetStyle( MatchStart()+(pText-yytext), MatchEnd(), STYLE_PREP );							
								BEGIN(PREPROCESSOR);
								pText++;
								bool bDec, bInc;
								checkPreprocessor( pText, m_langId, bDec, bInc );
								if( bDec ) levelDecrease();
								if( bInc ) levelIncrease();
							}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 75 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
{
			SetStyle(MatchStart(), MatchStart()+4, STYLE_KW );
			SetStyle(MatchEnd()-1, MatchEnd(), STYLE_SYMBOL );
			BEGIN(UID); 
	}
	YY_BREAK
/* VC++ message maps */
case 7:
YY_RULE_SETUP
#line 82 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_TEXT); levelIncrease(); 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 83 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_TEXT); levelDecrease();
	YY_BREAK
/* RC */
case 9:
YY_RULE_SETUP
#line 86 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_KW); levelIncrease(); 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 87 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_KW); levelDecrease();
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 89 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_AT); 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
if( isCppKeyword(yytext,m_langId) ) SetStyle(STYLE_KW); else SetStyle();
	YY_BREAK
/* numbers */
case 13:
#line 95 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
case 14:
#line 96 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
case 15:
#line 97 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
case 16:
YY_RULE_SETUP
#line 97 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_NUMBER);
	YY_BREAK
/* folding */
case 17:
YY_RULE_SETUP
#line 100 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_SYMBOL);	levelIncrease();
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 101 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_SYMBOL);	levelDecrease();
	YY_BREAK
/* folding */
case 19:
YY_RULE_SETUP
#line 104 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_SYMBOL);	levelIncrease();
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 105 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_SYMBOL);	levelDecrease();
	YY_BREAK
/* folding for IDL only ! */
case 21:
YY_RULE_SETUP
#line 108 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_SYMBOL); levelIncrease();
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_SYMBOL); levelDecrease();
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 111 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
BEGIN(SLCOMMENT); SetStyle(); levelIncrease();
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 113 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
BEGIN(SLCOMMENT); SetStyle(); levelDecrease();
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 115 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_SYMBOL);
	YY_BREAK
/* invalid chars - all second part of the ASCII table */
case 26:
YY_RULE_SETUP
#line 118 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(IStyler::styleInvalidText);
	YY_BREAK


case 27:
YY_RULE_SETUP
#line 122 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
BEGIN(INITIAL); SetStyle(); 
	YY_BREAK


case 28:
YY_RULE_SETUP
#line 125 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle();	BEGIN(INITIAL); levelDecrease();
	YY_BREAK


case 29:
YY_RULE_SETUP
#line 129 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(); BEGIN(INITIAL);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 130 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(); BEGIN(INITIAL);
	YY_BREAK


case 31:
YY_RULE_SETUP
#line 134 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(); BEGIN(INITIAL);
	YY_BREAK


/*escaped symbols*/
case 32:
#line 140 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
case 33:
#line 141 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
case 34:
#line 142 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
case 35:
YY_RULE_SETUP
#line 142 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle();
	YY_BREAK
/*invalid escaped symbol*/
case 36:
YY_RULE_SETUP
#line 145 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(IStyler::styleInvalidText);
	YY_BREAK
/*invalid end-of-line*/
case 37:
YY_RULE_SETUP
#line 148 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_UNQ); BEGIN(INITIAL);
	YY_BREAK


/*folding*/
case 38:
YY_RULE_SETUP
#line 153 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(); levelIncrease();
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 154 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(); levelDecrease();
	YY_BREAK
/* comments */
/* \/\/				BEGIN(SLCOMMENT); SetStyle(); */
/* \/\*				BEGIN(COMMENT);   SetStyle(); levelIncrease(); */
case 40:
YY_RULE_SETUP
#line 160 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle();
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 161 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
BEGIN(INITIAL);   SetStyle();
	YY_BREAK


case 42:
YY_RULE_SETUP
#line 165 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle();
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 166 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_UNQ); BEGIN(INITIAL);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 167 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(STYLE_SYMBOL); BEGIN(INITIAL);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 168 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle(IStyler::styleInvalidText);
	YY_BREAK


case 46:
#line 173 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
case 47:
#line 174 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
case 48:
#line 175 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
case 49:
YY_RULE_SETUP
#line 175 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
SetStyle();
	YY_BREAK

case 50:
YY_RULE_SETUP
#line 178 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"
ECHO;
	YY_BREAK
#line 1065 "C:\\work\\ape++\\src\\lexers\\LexerCPP.cpp"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(SLCOMMENT):
			case YY_STATE_EOF(STRING):
			case YY_STATE_EOF(CHAR):
			case YY_STATE_EOF(PREPROCESSOR):
			case YY_STATE_EOF(UID):
				yyterminate();
/* end of actions code                                                  */
/************************************************************************/
        case YY_END_OF_BUFFER: {
            /* Amount of text matched not including the EOB char. */
            int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;
    
            /* Undo the effects of YY_DO_BEFORE_ACTION. */
            *yy_cp = yy_hold_char;
            YY_RESTORE_YY_MORE_OFFSET

            if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
            {/* We're scanning a new file or input source.  It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex().  If so, then we have to assure
             * consistency between yy_current_buffer and our
             * globals.  Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.*/
                yy_n_chars = yy_current_buffer->yy_n_chars;
                yy_current_buffer->yy_input_file = yyin;
                yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
            }

            /* Note that here we test for yy_c_buf_p "<=" to the position
             * of the first EOB in the buffer, since yy_c_buf_p will
             * already have been incremented past the NUL character
             * (since all states make transitions on EOB to the
             * end-of-buffer state).  Contrast this with the test
             * in input().*/
            if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            {/* This was really a NUL. */
                yy_state_type yy_next_state;

                yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state();

            /* Okay, we're now positioned to make the NUL
             * transition.  We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).*/

                yy_next_state = yy_try_NUL_trans( yy_current_state );

                yy_bp = yytext_ptr + YY_MORE_ADJ;

                if( yy_next_state )
                {/* Consume the NUL. */
                    yy_cp = ++yy_c_buf_p;
                    yy_current_state = yy_next_state;
                    goto yy_match;
                } else {
/************************************************************************/
/* start ofcode to do back-up for compressed tables and set up yy_cp    */              
				yy_cp = yy_c_buf_p;
/* end if code to do back-up for compressed tables and set up yy_cp     */              
/************************************************************************/
                    goto yy_find_action;
                }
            } else
            switch ( yy_get_next_buffer() ) {
            case EOB_ACT_END_OF_FILE: {
                yy_did_buffer_switch_on_eof = 0;
                if( yywrap() ) {
                /* Note: because we've taken care in
                 * yy_get_next_buffer() to have set up
                 * yytext, we can now set up
                 * yy_c_buf_p so that if some total
                 * hoser (like flex itself) wants to
                 * call the scanner after we return the
                 * YY_NULL, it'll still work - another
                 * YY_NULL will get returned.*/
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
                    yy_act = YY_STATE_EOF(YY_START);
                    goto do_action;
                } else {
                    if( !yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
                }
                break;}
            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;
                yy_current_state = yy_get_previous_state();
                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_match;
            case EOB_ACT_LAST_MATCH:
                yy_c_buf_p = &yy_current_buffer->yy_ch_buf[yy_n_chars];
                yy_current_state = yy_get_previous_state();
                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_find_action;
            }
            break;}
        default:
            YY_FATAL_ERROR("fatal flex scanner internal error--no action found" );
        } /* end of action switch */
    } /* end of scanning one token */
} /* end of yylex */
#undef YY_DECL

yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
    yyin            = arg_yyin;
    yyout           = arg_yyout;
    yy_c_buf_p      = 0;
    yy_init         = 1;
    yy_start        = 0;
    yy_flex_debug   = 0;
    yylineno        = 1;    // this will only get updated if %option yylineno

    yy_did_buffer_switch_on_eof					= 0;

    yy_looking_for_trail_begin                  = 0;
    yy_more_flag                                = 0;
    yy_more_len                                 = 0;
    yy_more_offset = yy_prev_more_offset        = 0;

    yy_start_stack_ptr = yy_start_stack_depth   = 0;
    yy_start_stack                              = 0;

    yy_current_buffer                           = 0;

#ifdef YY_USES_REJECT
    yy_state_buf                                = new yy_state_type[YY_BUF_SIZE + 2];
#else
    yy_state_buf                                = 0;
#endif
}

yyFlexLexer::~yyFlexLexer()
{
    delete yy_state_buf;
    yy_delete_buffer( yy_current_buffer );
}

void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
    if ( new_in ) {
        yy_delete_buffer( yy_current_buffer );
        yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
    }

    if ( new_out )
        yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif /* !YY_INTERACTIVE */
{
    if( yyin->eof() || yyin->fail() )
        return 0;

#ifdef YY_INTERACTIVE
    yyin->get( buf[0] );
    if( yyin->eof() )
        return 0;
    if( yyin->bad() )
        return -1;
    return 1;
#else  /* YY_INTERACTIVE */
    (void) yyin->read( buf, max_size );
    if( yyin->bad() )
        return -1;
    else
        return yyin->gcount();
#endif /* !YY_INTERACTIVE */
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
    (void) yyout->write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *  EOB_ACT_LAST_MATCH -
 *  EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *  EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    register char *dest = yy_current_buffer->yy_ch_buf;
    register char *source = yytext_ptr;
    register int number_to_move, i;
    int ret_val;

    if( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
        YY_FATAL_ERROR("fatal flex scanner internal error--end of buffer missed" );

    if( yy_current_buffer->yy_fill_buffer == 0 )
    { /* Don't try to fill the buffer, so this is an EOF. */
        if( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 ) {
        /* We matched a single character, the EOB, so
         *  treat this as a final EOF.
         */
            return EOB_ACT_END_OF_FILE;
        } else {
        /* We matched some text prior to the EOB, first
         * process it.
         */
            return EOB_ACT_LAST_MATCH;
        }
    }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

    for( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

    if( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
    /* don't do the read, it's not guaranteed to return an EOF,
     * just force an EOF
     */
        yy_current_buffer->yy_n_chars = yy_n_chars = 0;

    else {
        int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;
        while ( num_to_read <= 0 ) {
            /* Not enough room in the buffer - grow it. */
        #ifdef YY_USES_REJECT
            YY_FATAL_ERROR("input buffer overflow, can't enlarge buffer because scanner uses REJECT");
        #else
            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = yy_current_buffer;

            int yy_c_buf_p_offset = (int)(yy_c_buf_p - b->yy_ch_buf);

            if( b->yy_is_our_buffer ) {
                int new_size = b->yy_buf_size * 2;
                if ( new_size <= 0 )
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char *)
                    /* Include room in for 2 EOB chars. */
                    yy_flex_realloc( (void *) b->yy_ch_buf, b->yy_buf_size + 2 );
            } else /* Can't grow it, we don't own it. */
                b->yy_ch_buf = 0;

            if ( ! b->yy_ch_buf )
                YY_FATAL_ERROR("fatal error - scanner input buffer overflow" );

            yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];
            num_to_read = yy_current_buffer->yy_buf_size -
                        number_to_move - 1;
        #endif
        }

        if( num_to_read > YY_READ_BUF_SIZE )
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]), yy_n_chars, num_to_read );
        yy_current_buffer->yy_n_chars = yy_n_chars;
    }

    if( yy_n_chars == 0 ) {
        if( number_to_move == YY_MORE_ADJ ) {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart( yyin );
        } else {
            ret_val = EOB_ACT_LAST_MATCH;
            yy_current_buffer->yy_buffer_status = YY_BUFFER_EOF_PENDING;
        }
    } else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

    return ret_val;
}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
{
    register yy_state_type yy_current_state;
    register char *yy_cp;
/*********************************************************************/
/* start of code to get the start state into yy_current_state        */
	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;
/* end of start of code to get the start state into yy_current_state */
/*********************************************************************/

    for( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
    {
/*********************************************************************/
/* start of code to find the next state                              */     
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 171 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
/* end of code to find the next state                                */     
/*********************************************************************/
    }

    return yy_current_state;
}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *  next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
    register int yy_is_jam;
/*********************************************************************/
/* start of code to find the next state, and perhaps do backing up   */

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 171 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 170);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;
/* end ofcode to find the next state, and perhaps do backing up      */
/*********************************************************************/
    return yy_is_jam ? 0 : yy_current_state;
}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
{
    register char *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if( yy_cp < yy_current_buffer->yy_ch_buf + 2 ) {
    /* need to shift things up to make room */
    /* +2 for EOB chars. */
        register int number_to_move = yy_n_chars + 2;
        register char *dest = &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
        register char *source = &yy_current_buffer->yy_ch_buf[number_to_move];

        while( source > yy_current_buffer->yy_ch_buf )
            *--dest = *--source;

        yy_cp += (int) (dest - source);
        yy_bp += (int) (dest - source);
        yy_current_buffer->yy_n_chars = yy_n_chars = yy_current_buffer->yy_buf_size;

        if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
            YY_FATAL_ERROR( "flex scanner push-back overflow" );
    }
    *--yy_cp = (char) c;

/****************************/
/* start of update yylineno */
/* end of update yylineno   */
/****************************/

    yytext_ptr = yy_bp;
    yy_hold_char = *yy_cp;
    yy_c_buf_p = yy_cp;
}


int yyFlexLexer::yyinput()
{
    int c;
    *yy_c_buf_p = yy_hold_char;

    if( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR ) {
    /* yy_c_buf_p now points to the character we want to return.
     * If this occurs *before* the EOB characters, then it's a
     * valid NUL; if not, then we've hit the end of the buffer.
     */
        if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
        /* This was really a NUL. */
            *yy_c_buf_p = '\0';

        else {
        /* need more input */
            int offset = yy_c_buf_p - yytext_ptr;
            ++yy_c_buf_p;

            switch ( yy_get_next_buffer() ) {
            case EOB_ACT_LAST_MATCH:
                /* This happens because yy_g_n_b()
                 * sees that we've accumulated a
                 * token and flags that we need to
                 * try matching the token before
                 * proceeding.  But for input(),
                 * there's no matching to consider.
                 * So convert the EOB_ACT_LAST_MATCH
                 * to EOB_ACT_END_OF_FILE.*/

                /* Reset buffer status. */
                yyrestart( yyin );

                /* fall through */

            case EOB_ACT_END_OF_FILE:
                {
                    if ( yywrap() )
                        return EOF;

                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;                    
                        
                #ifdef __cplusplus
                    return yyinput();
                #else
                    return input();
                #endif
                }

            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p = yytext_ptr + offset;
                break;
            }
        }
    }

    c = *(unsigned char *) yy_c_buf_p;  /* cast for 8-bit char's */
    *yy_c_buf_p = '\0'; /* preserve yytext */
    yy_hold_char = *++yy_c_buf_p;

/************************************/
/* start of update BOL and yylineno */
	yy_current_buffer->yy_at_bol = (c == '\n');
/* end of update BOL and yylineno   */
/************************************/

    return c;
}

void yyFlexLexer::yyrestart( std::istream* input_file )
{
    if ( ! yy_current_buffer )
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    if( yy_current_buffer == new_buffer )
        return;

    if( yy_current_buffer ) {
    /* Flush out information for old buffer. */
        *yy_c_buf_p = yy_hold_char;
        yy_current_buffer->yy_buf_pos = yy_c_buf_p;
        yy_current_buffer->yy_n_chars = yy_n_chars;
    }

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
}

void yyFlexLexer::yy_load_buffer_state()
{
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
}

YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
    if( ! b ) YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
    if( ! b->yy_ch_buf ) YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_is_our_buffer = 1;

    yy_init_buffer( b, file );

    return b;
}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    if ( ! b )
        return;

    if ( b == yy_current_buffer )
        yy_current_buffer = (YY_BUFFER_STATE) 0;

    if ( b->yy_is_our_buffer )
        yy_flex_free( (void *) b->yy_ch_buf );

    yy_flex_free( (void *) b );
}

extern "C" int isatty YY_PROTO(( int ));

void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )
{
    yy_flush_buffer( b );

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

    b->yy_is_interactive = 0;
}

void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    if ( ! b )
        return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.*/
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if( b == yy_current_buffer )
        yy_load_buffer_state();
}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif /* !YY_NO_SCAN_BYTES */


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
{
    if( yy_start_stack_ptr >= yy_start_stack_depth ) {
        yy_size_t new_size;

        yy_start_stack_depth += YY_START_STACK_INCR;
        new_size = yy_start_stack_depth * sizeof(int);

        if( !yy_start_stack )
            yy_start_stack = (int *) yy_flex_alloc( new_size );
        else
            yy_start_stack = (int *) yy_flex_realloc((void *)yy_start_stack, new_size);

        if( !yy_start_stack )
            YY_FATAL_ERROR("out of memory expanding start-condition stack" );
    }
    yy_start_stack[yy_start_stack_ptr++] = YY_START;
    BEGIN(new_state);
}
#endif /* !YY_NO_PUSH_STATE */


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
{
    if( --yy_start_stack_ptr < 0 )
        YY_FATAL_ERROR( "start-condition stack underflow" );
    BEGIN(yy_start_stack[yy_start_stack_ptr]);
}
#endif /* !YY_NO_POP_STATE */


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
{
	if( yy_start_stack_ptr == 0 )
		return YY_START;
    return yy_start_stack[yy_start_stack_ptr - 1];
}
#endif /* !YY_NO_TOP_STATE */

#ifndef YY_EXIT_FAILURE
    #define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError(yyconst char msg[])
{
    cerr << msg << '\n';
    exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */
#undef yyless
#define yyless(n) \
    do {\
        /* Undo effects of setting up yytext. */ \
        yytext[yyleng] = yy_hold_char; \
        yy_c_buf_p = yytext + n; \
        yy_hold_char = *yy_c_buf_p; \
        *yy_c_buf_p = '\0'; \
        yyleng = n; \
    } while ( 0 )


/* Internal utility routines. */
#ifndef yytext_ptr
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
{
    register int i;
    for ( i = 0; i < n; ++i )
        s1[i] = s2[i];
}
#endif /* yytext_ptr */

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen( yyconst char *s )
{
    register int n;
    for( n = 0; s[n]; ++n );

    return n;
}
#endif /* YY_NEED_STRLEN */


static void *yy_flex_alloc( yy_size_t size )
{
    return (void*)malloc( size );
}

static void *yy_flex_realloc( void *ptr, yy_size_t size )
{
/* The cast to (char *) in the following accommodates both
 * implementations that use char* generic pointers, and those
 * that use void* generic pointers.  It works with the latter
 * because both ANSI C and C++ allow castless assignment from
 * any pointer type to void*, and deal with argument conversions
 * as though doing an assignment.*/
    return (void *) realloc( (char *) ptr, size );
}

static void yy_flex_free( void *ptr )
{
    free( ptr );
}

#if YY_MAIN
    int main()
    {
        FlexLexer* lexer = new yyFlexLexer;
        while(lexer->yylex() != 0);
        delete lexer;
        return 0;
    }
#endif
#line 178 "C:\\work\\ape++\\src\\lexers\\LexerCPP.L"

/*************************************************************************************/

int CSciLexer<yyFlexLexer>::StateToStyle(int nState) {
	switch(nState) {
		case INITIAL:		return STYLE_TEXT;
		case SLCOMMENT:
		case COMMENT:		return STYLE_COMMENT;
		case STRING:		return STYLE_STRING;
		case CHAR:			return STYLE_CHAR;
		case PREPROCESSOR:	return STYLE_PREP;
		case UID:			return STYLE_UID;
	}
	return 0;
}