#define yyFlexLexer nsis_FlexLexer
#define yywrap nsis_wrap

#line 5 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: k:\\backup\\cvsroot/ape/lexer/Lexer.skl,v 1.1 2000/11/15 13:38:44 Basil_Burdo Exp $
 */
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#undef	yywrap

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
    #ifndef __cplusplus
        #define __cplusplus
    #endif
#endif


#ifdef __cplusplus
    #include <stdlib.h>
//  #include <unistd.h>
    class istream;

    /* Use prototypes in function declarations. */
    #define YY_USE_PROTOS
    /* The "const" storage-class-modifier is valid. */
    #define YY_USE_CONST
#else   /* ! __cplusplus */
    #if __STDC__
        #define YY_USE_PROTOS
        #define YY_USE_CONST
    #endif  /* __STDC__ */
#endif  /* ! __cplusplus */

#ifdef YY_USE_CONST
    #define yyconst const
#else
    #define yyconst
#endif

#ifdef YY_USE_PROTOS
    #define YY_PROTO(proto) proto
#else
    #define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.*/
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.*/
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.*/
#define YY_START			((yy_start - 1) / 2)
#define YYSTATE				YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *  if ( condition_holds )
 *      yyless( 5 );
 *  else
 *      do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        *yy_cp = yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).*/
typedef unsigned int yy_size_t;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
    { \
        if ( ! yy_current_buffer ) \
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
        yy_current_buffer->yy_is_interactive = is_interactive; \
    }

#define yy_set_bol(at_bol) \
    { \
        if ( ! yy_current_buffer ) \
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
        yy_current_buffer->yy_at_bol = at_bol; \
    }

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

/************************************************************************/
/* start of yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init  */
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int CSciLexer<yyFlexLexer>::yylex()
/* end of yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init    */
/************************************************************************/


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
    yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
    yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yy_c_buf_p = yy_cp;

/*********************************************************************************/
/* start of data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 29
#define YY_END_OF_BUFFER 30
static yyconst short int yy_accept[88] =
    {   0,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   30,   28,   26,   27,
       28,   14,    7,    2,   14,    8,   14,   13,    1,   12,
       12,    9,   15,   26,   14,   12,   12,   28,   25,   17,
       28,   19,   28,   20,   28,   28,   21,   22,   24,   28,
       28,    1,   28,   26,   27,    5,    0,    0,    3,   13,
       12,   12,   15,   26,    0,    0,    0,   10,    0,   12,
       11,   12,   16,   25,   17,   19,   18,    0,   24,   23,
        0,    6,    0,    0,    0,    4,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,    9,   10,    9,
        9,   11,    9,    9,    9,    9,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,    9,
        9,    9,    9,    1,   16,   16,   16,   16,   16,   16,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
        9,   18,    9,    1,   17,   19,   20,   20,   20,   20,

       20,   20,   21,   21,   21,   21,   21,   21,   21,   22,
       21,   21,   21,   22,   21,   21,   21,   21,   21,   21,
       21,   21,   23,    9,   24,    9,    1,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25
    } ;

static yyconst int yy_meta[26] =
    {   0,
        1,    2,    1,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    4,    5,    1,    6,    6,    7,    1,    8,
        8,    8,    7,    9,    1
    } ;

static yyconst short int yy_base[96] =
    {   0,
        0,   24,   45,   66,   24,   27,   86,    0,   26,   27,
       33,   36,  129,  128,  102,    0,  138,  201,  135,  201,
      133,  201,  201,  201,   35,  201,  124,   44,  201,  108,
       58,  201,  101,   49,  117,  129,   59,  106,    0,  201,
      113,  201,  109,  201,   58,   81,  201,  201,  201,  105,
       90,  201,   92,   89,  201,   75,   58,    0,  201,   87,
        0,    0,   48,   97,   61,  108,    0,  112,  109,    0,
      201,    0,  201,    0,  201,  201,  201,   56,  201,  201,
       47,  201,   19,  113,   10,  201,  201,  151,  157,  164,
      171,  176,  179,  186,  191

    } ;

static yyconst short int yy_def[96] =
    {   0,
       87,    1,   88,   88,    4,    4,    4,    7,    7,    7,
        7,    7,    4,    4,    4,   15,   87,   87,   87,   87,
       87,   87,   87,   87,   89,   87,   87,   87,   87,   87,
       30,   87,   87,   90,   91,   87,   36,   87,   92,   87,
       87,   87,   87,   87,   89,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   89,   87,   93,   87,   87,
       30,   31,   87,   90,   91,   94,   65,   87,   87,   36,
       87,   37,   87,   92,   87,   87,   87,   87,   87,   87,
       87,   87,   95,   94,   95,   87,    0,   87,   87,   87,
       87,   87,   87,   87,   87

    } ;

static yyconst short int yy_nxt[227] =
    {   0,
       18,   19,   20,   21,   22,   23,   24,   25,   22,   26,
       22,   27,   28,   22,   29,   30,   31,   22,   32,   30,
       31,   31,   22,   22,   33,   34,   40,   41,   35,   40,
       41,   18,   18,   86,   18,   47,   47,   18,   18,   36,
       37,   18,   86,   36,   37,   37,   19,   20,   21,   80,
       64,   48,   57,   65,   48,   38,   60,   58,   77,   60,
       39,   39,   67,   60,   39,   39,   39,   19,   20,   21,
       62,   72,   63,   62,   72,   57,   38,   62,   72,   82,
       58,   39,   39,   77,   78,   39,   39,   39,   42,   43,
       54,   44,   87,   45,   80,   81,   18,   87,   64,   60,

       59,   65,   60,   46,   49,   50,   60,   79,   24,   69,
       69,   76,   18,   51,   69,   75,   52,   73,   67,   53,
       61,   71,   71,   61,   62,   63,   71,   61,   62,   62,
       69,   68,   68,   68,   59,   55,   54,   87,   18,   18,
       87,   70,   71,   87,   70,   72,   87,   87,   70,   72,
       72,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       56,   87,   56,   56,   56,   66,   66,   87,   87,   66,
       87,   66,   68,   87,   87,   87,   87,   87,   68,   74,
       87,   74,   87,   74,   83,   87,   83,   84,   87,   84,
       84,   84,   87,   84,   85,   87,   85,   87,   85,   85,

       17,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87
    } ;

static yyconst short int yy_chk[227] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    5,    5,    2,    6,
        6,    9,   10,   85,    5,    9,   10,    6,   11,    2,
        2,   12,   83,    2,    2,    2,    3,    3,    3,   81,
       34,   11,   25,   34,   12,    3,   28,   25,   78,   28,
        3,    3,   65,   28,    3,    3,    3,    4,    4,    4,
       31,   37,   63,   31,   37,   45,    4,   31,   37,   57,
       45,    4,    4,   46,   46,    4,    4,    4,    7,    7,
       54,    7,   56,    7,   53,   53,    7,   56,   64,   60,

       51,   64,   60,    7,   15,   15,   60,   50,   15,   66,
       69,   43,   15,   15,   84,   41,   15,   38,   35,   15,
       30,   66,   69,   30,   30,   33,   84,   30,   30,   30,
       36,   68,   68,   68,   27,   21,   19,   17,   14,   13,
        0,   36,   36,    0,   36,   36,    0,    0,   36,   36,
       36,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       89,    0,   89,   89,   89,   90,   90,    0,    0,   90,
        0,   90,   91,    0,    0,    0,    0,    0,   91,   92,
        0,   92,    0,   92,   93,    0,   93,   94,    0,   94,
       94,   94,    0,   94,   95,    0,   95,    0,   95,   95,

       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
#define INITIAL 0
#line 2 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
#include "LexBase.h"
#define COMMENT 1
#define SLCOMMENT 2
#define STRING 3
#define STRING2 4
#define STRING3 5
#define VAR 6
#define PREPROCESSOR 7

// without - "'	esc []-\/   !
#line 24 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"

#define STYLE_TEXT			0
#define STYLE_KW			1
#define STYLE_COMMENT		2
#define STYLE_SYMBOL		3
#define STYLE_STRING		4
#define STYLE_UNQ			5
#define STYLE_NUMBER		6
#define STYLE_VAR			7
#define STYLE_PREP			8
#define STYLE_LABEL			9

void checkNsisFoldLevel( const char* text, bool& bInc, bool& bDec ) {
	bInc = bDec = false;
	if( !strcmpi(text,"Section") || 
		!strcmpi(text,"SubSection") || 
		!strcmpi(text,"Function") || 
		!strcmpi(text,"SectionGroup")
		)
		bInc=true;
	if( !strcmpi(text,"SectionEnd") || 
		!strcmpi(text,"SubSectionEnd") || 		
		!strcmpi(text,"FunctionEnd") || 
		!strcmpi(text,"SectionGroupEnd")
		)
		bDec=true;
}

void checkNsisPrep( const char* text, bool& bDec, bool& bInc ) {
	bDec = bInc = false;
	char ch = text[0];

	switch( ch ) {
		case 'i': 
			if( !strcmp(text,"ifdef") || !strcmp(text,"ifndef") ) bInc = true;
			break;
		case 'e':
			if( !strcmp(text,"endif") ) bDec = true;
			if( !strcmp(text,"elif") || !strcmp(text,"else") ) {
				bDec=true; 
				bInc=true; 
			}
			break;
		case 'm':
			if( !strcmp(text,"macro") ) bInc=true;
			if( !strcmp(text,"macroend") ) bDec=true;
			break;
	}
}

bool isKeywordNSIS( const char* szKW ); // defined in lexNSIS

#line 415 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.cpp"
/* end of data tables for the DFA and the user's section 1 definitions go here   */
/*********************************************************************************/


#ifndef yytext_ptr
    static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
    static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
    static int yy_start_stack_ptr = 0;
    static int yy_start_stack_depth = 0;
    static int *yy_start_stack = 0;
    #ifndef YY_NO_PUSH_STATE
        static void yy_push_state YY_PROTO(( int new_state ));
    #endif
    #ifndef YY_NO_POP_STATE
        static void yy_pop_state YY_PROTO(( void ));
    #endif
    #ifndef YY_NO_TOP_STATE
        static int yy_top_state YY_PROTO(( void ));
    #endif
#else
    #define YY_NO_PUSH_STATE    1
    #define YY_NO_POP_STATE     1
    #define YY_NO_TOP_STATE     1
#endif

#ifdef YY_MALLOC_DECL
    YY_MALLOC_DECL
#else
    #if __STDC__
        #ifndef __cplusplus
            #include <stdlib.h>
        #endif
    #else
        /* Just try to get by without declaring the routines.  This will fail
         * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
         * or sizeof(void*) != sizeof(int).
         */
    #endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
    #define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
    #define ECHO LexerOutput( yytext, yyleng )
#endif /* !ECHO */

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
    #define YY_INPUT(buf,result,max_size) \
        if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
            YY_FATAL_ERROR( "input in flex scanner failed" );
#endif /* !YY_INPUT */

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.*/
#ifndef yyterminate
    #define yyterminate() return YY_NULL
#endif /* !yyterminate */

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
    #define YY_START_STACK_INCR 25
#endif /* !YY_START_STACK_INCR */

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
    #define YY_FATAL_ERROR(msg) LexerError( msg )
#endif /* !YY_FATAL_ERROR */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
    #define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.*/
#ifndef YY_USER_ACTION
    #define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
    #define YY_BREAK    break;
#endif

/************************************************************************/
/* start of YY_RULE_SETUP definition                                    */
#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION
/* end of YY_RULE_SETUP definition                                      */
/************************************************************************/

YY_DECL
{
    register yy_state_type yy_current_state;
    register char *yy_cp, *yy_bp;
    register int yy_act;

/************************************************************************/
/* start of user's declarations                                         */
#line 78 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"

 /*************************************************************************************/

#line 542 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.cpp"
/* end of user's declarations                                           */
/************************************************************************/

    if( yy_init ) {
        yy_init = 0;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif /* YY_USER_INIT */

        if( !yy_start )
            yy_start = 1;   /* first start state */

        if( !yyin )
            yyin = &cin;

        if( !yyout )
            yyout = &cout;

        if( !yy_current_buffer )
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

        yy_load_buffer_state();
    }

    while( 1 )      /* loops until end-of-file is reached */
    {
/************************************************************************/
/* start of yymore()-related code                                       */
/* end of yymore()-related code                                         */
/************************************************************************/
        
        yy_cp = yy_c_buf_p;

        *yy_cp = yy_hold_char; /* Support of yytext. */

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run. */
        yy_bp = yy_cp;

/************************************************************************/
/* start of code to set up and find next match                          */
		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 88 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 201 );
/* end of code to set up and find next match                            */
/************************************************************************/

yy_find_action:

/************************************************************************/
/* start of code to find the action number                              */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}
/* end of code to find the action number                                */
/************************************************************************/

        YY_DO_BEFORE_ACTION;

/************************************************************************/
/* start of code for yylineno update                                    */
/* end if code for yylineno update                                      */
/************************************************************************/

do_action:  /* This label is used only to access EOF actions. */

/************************************************************************/
/* start of debug code                                                  */
/* end of debug code                                                    */
/************************************************************************/
        switch ( yy_act ) { /* beginning of action switch */
/************************************************************************/
/* start of actions code                                                */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;


case 1:
YY_RULE_SETUP
#line 82 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
BEGIN(SLCOMMENT); SetStyle();
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 83 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
BEGIN(SLCOMMENT); SetStyle();
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 84 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
BEGIN(COMMENT); SetStyle(); levelIncrease();
	YY_BREAK


case 4:
YY_RULE_SETUP
#line 88 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle(STYLE_VAR);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 89 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle(STYLE_VAR);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 90 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle(STYLE_VAR);
	YY_BREAK


case 7:
YY_RULE_SETUP
#line 94 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
BEGIN(STRING);	  SetStyle();
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 95 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
BEGIN(STRING2);	  SetStyle();
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 96 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
BEGIN(STRING3);	  SetStyle();
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 98 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
{ //preprocessor
								char* pText;
								for( pText=yytext; *pText!='!'; pText++ );
								SetStyle( MatchStart(), MatchStart()+(pText-yytext), STYLE_TEXT );
								SetStyle( MatchStart()+(pText-yytext), MatchEnd(), STYLE_PREP );							
								BEGIN(PREPROCESSOR);
								pText++;
								bool bDec, bInc;
								checkNsisPrep( pText, bDec, bInc );
								if( bDec ) levelDecrease();
								if( bInc ) levelIncrease();
							}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 111 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle(STYLE_LABEL);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 113 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
{
				if( isKeywordNSIS(yytext) ) SetStyle(STYLE_KW); else SetStyle();
				bool bInc, bDec; 
				checkNsisFoldLevel(yytext,bInc,bDec);
				if( bDec ) levelDecrease();
				if( bInc ) levelIncrease();
			}	
	YY_BREAK
/* numbers */
case 13:
YY_RULE_SETUP
#line 122 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle(STYLE_NUMBER);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 124 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle(STYLE_SYMBOL);
	YY_BREAK
/* invalid chars - all second part of the ASCII table */
case 15:
YY_RULE_SETUP
#line 127 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle(IStyler::styleInvalidText);
	YY_BREAK


case 16:
YY_RULE_SETUP
#line 131 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle();	BEGIN(INITIAL); levelDecrease();
	YY_BREAK


case 17:
YY_RULE_SETUP
#line 135 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
BEGIN(INITIAL); SetStyle(); 
	YY_BREAK


case 18:
YY_RULE_SETUP
#line 139 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle();
	YY_BREAK
/*invalid end-of-line*/
case 19:
YY_RULE_SETUP
#line 142 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle(STYLE_UNQ); BEGIN(INITIAL);
	YY_BREAK


case 20:
YY_RULE_SETUP
#line 145 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle(); BEGIN(INITIAL);
	YY_BREAK


case 21:
YY_RULE_SETUP
#line 148 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle(); BEGIN(INITIAL);
	YY_BREAK


case 22:
YY_RULE_SETUP
#line 151 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle(); BEGIN(INITIAL);
	YY_BREAK


case 23:
YY_RULE_SETUP
#line 155 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle();
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 157 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
BEGIN(INITIAL);   SetStyle();
	YY_BREAK


case 25:
#line 163 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
case 26:
#line 164 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
case 27:
#line 165 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
case 28:
YY_RULE_SETUP
#line 165 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
SetStyle();
	YY_BREAK

case 29:
YY_RULE_SETUP
#line 168 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"
ECHO;
	YY_BREAK
#line 824 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(SLCOMMENT):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(STRING2):
case YY_STATE_EOF(STRING3):
case YY_STATE_EOF(VAR):
case YY_STATE_EOF(PREPROCESSOR):
	yyterminate();
/* end of actions code                                                  */
/************************************************************************/
        case YY_END_OF_BUFFER: {
            /* Amount of text matched not including the EOB char. */
            int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;
    
            /* Undo the effects of YY_DO_BEFORE_ACTION. */
            *yy_cp = yy_hold_char;
            YY_RESTORE_YY_MORE_OFFSET

            if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
            {/* We're scanning a new file or input source.  It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex().  If so, then we have to assure
             * consistency between yy_current_buffer and our
             * globals.  Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.*/
                yy_n_chars = yy_current_buffer->yy_n_chars;
                yy_current_buffer->yy_input_file = yyin;
                yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
            }

            /* Note that here we test for yy_c_buf_p "<=" to the position
             * of the first EOB in the buffer, since yy_c_buf_p will
             * already have been incremented past the NUL character
             * (since all states make transitions on EOB to the
             * end-of-buffer state).  Contrast this with the test
             * in input().*/
            if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            {/* This was really a NUL. */
                yy_state_type yy_next_state;

                yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state();

            /* Okay, we're now positioned to make the NUL
             * transition.  We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).*/

                yy_next_state = yy_try_NUL_trans( yy_current_state );

                yy_bp = yytext_ptr + YY_MORE_ADJ;

                if( yy_next_state )
                {/* Consume the NUL. */
                    yy_cp = ++yy_c_buf_p;
                    yy_current_state = yy_next_state;
                    goto yy_match;
                } else {
/************************************************************************/
/* start ofcode to do back-up for compressed tables and set up yy_cp    */              
				yy_cp = yy_c_buf_p;
/* end if code to do back-up for compressed tables and set up yy_cp     */              
/************************************************************************/
                    goto yy_find_action;
                }
            } else
            switch ( yy_get_next_buffer() ) {
            case EOB_ACT_END_OF_FILE: {
                yy_did_buffer_switch_on_eof = 0;
                if( yywrap() ) {
                /* Note: because we've taken care in
                 * yy_get_next_buffer() to have set up
                 * yytext, we can now set up
                 * yy_c_buf_p so that if some total
                 * hoser (like flex itself) wants to
                 * call the scanner after we return the
                 * YY_NULL, it'll still work - another
                 * YY_NULL will get returned.*/
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
                    yy_act = YY_STATE_EOF(YY_START);
                    goto do_action;
                } else {
                    if( !yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
                }
                break;}
            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;
                yy_current_state = yy_get_previous_state();
                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_match;
            case EOB_ACT_LAST_MATCH:
                yy_c_buf_p = &yy_current_buffer->yy_ch_buf[yy_n_chars];
                yy_current_state = yy_get_previous_state();
                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_find_action;
            }
            break;}
        default:
            YY_FATAL_ERROR("fatal flex scanner internal error--no action found" );
        } /* end of action switch */
    } /* end of scanning one token */
} /* end of yylex */
#undef YY_DECL

yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
    yyin            = arg_yyin;
    yyout           = arg_yyout;
    yy_c_buf_p      = 0;
    yy_init         = 1;
    yy_start        = 0;
    yy_flex_debug   = 0;
    yylineno        = 1;    // this will only get updated if %option yylineno

    yy_did_buffer_switch_on_eof					= 0;

    yy_looking_for_trail_begin                  = 0;
    yy_more_flag                                = 0;
    yy_more_len                                 = 0;
    yy_more_offset = yy_prev_more_offset        = 0;

    yy_start_stack_ptr = yy_start_stack_depth   = 0;
    yy_start_stack                              = 0;

    yy_current_buffer                           = 0;

#ifdef YY_USES_REJECT
    yy_state_buf                                = new yy_state_type[YY_BUF_SIZE + 2];
#else
    yy_state_buf                                = 0;
#endif
}

yyFlexLexer::~yyFlexLexer()
{
    delete yy_state_buf;
    yy_delete_buffer( yy_current_buffer );
}

void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
    if ( new_in ) {
        yy_delete_buffer( yy_current_buffer );
        yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
    }

    if ( new_out )
        yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif /* !YY_INTERACTIVE */
{
    if( yyin->eof() || yyin->fail() )
        return 0;

#ifdef YY_INTERACTIVE
    yyin->get( buf[0] );
    if( yyin->eof() )
        return 0;
    if( yyin->bad() )
        return -1;
    return 1;
#else  /* YY_INTERACTIVE */
    (void) yyin->read( buf, max_size );
    if( yyin->bad() )
        return -1;
    else
        return yyin->gcount();
#endif /* !YY_INTERACTIVE */
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
    (void) yyout->write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *  EOB_ACT_LAST_MATCH -
 *  EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *  EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    register char *dest = yy_current_buffer->yy_ch_buf;
    register char *source = yytext_ptr;
    register int number_to_move, i;
    int ret_val;

    if( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
        YY_FATAL_ERROR("fatal flex scanner internal error--end of buffer missed" );

    if( yy_current_buffer->yy_fill_buffer == 0 )
    { /* Don't try to fill the buffer, so this is an EOF. */
        if( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 ) {
        /* We matched a single character, the EOB, so
         *  treat this as a final EOF.
         */
            return EOB_ACT_END_OF_FILE;
        } else {
        /* We matched some text prior to the EOB, first
         * process it.
         */
            return EOB_ACT_LAST_MATCH;
        }
    }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

    for( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

    if( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
    /* don't do the read, it's not guaranteed to return an EOF,
     * just force an EOF
     */
        yy_current_buffer->yy_n_chars = yy_n_chars = 0;

    else {
        int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;
        while ( num_to_read <= 0 ) {
            /* Not enough room in the buffer - grow it. */
        #ifdef YY_USES_REJECT
            YY_FATAL_ERROR("input buffer overflow, can't enlarge buffer because scanner uses REJECT");
        #else
            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = yy_current_buffer;

            int yy_c_buf_p_offset = (int)(yy_c_buf_p - b->yy_ch_buf);

            if( b->yy_is_our_buffer ) {
                int new_size = b->yy_buf_size * 2;
                if ( new_size <= 0 )
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char *)
                    /* Include room in for 2 EOB chars. */
                    yy_flex_realloc( (void *) b->yy_ch_buf, b->yy_buf_size + 2 );
            } else /* Can't grow it, we don't own it. */
                b->yy_ch_buf = 0;

            if ( ! b->yy_ch_buf )
                YY_FATAL_ERROR("fatal error - scanner input buffer overflow" );

            yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];
            num_to_read = yy_current_buffer->yy_buf_size -
                        number_to_move - 1;
        #endif
        }

        if( num_to_read > YY_READ_BUF_SIZE )
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]), yy_n_chars, num_to_read );
        yy_current_buffer->yy_n_chars = yy_n_chars;
    }

    if( yy_n_chars == 0 ) {
        if( number_to_move == YY_MORE_ADJ ) {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart( yyin );
        } else {
            ret_val = EOB_ACT_LAST_MATCH;
            yy_current_buffer->yy_buffer_status = YY_BUFFER_EOF_PENDING;
        }
    } else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

    return ret_val;
}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
{
    register yy_state_type yy_current_state;
    register char *yy_cp;
/*********************************************************************/
/* start of code to get the start state into yy_current_state        */
	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
/* end of start of code to get the start state into yy_current_state */
/*********************************************************************/

    for( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
    {
/*********************************************************************/
/* start of code to find the next state                              */     
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 88 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
/* end of code to find the next state                                */     
/*********************************************************************/
    }

    return yy_current_state;
}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *  next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
    register int yy_is_jam;
/*********************************************************************/
/* start of code to find the next state, and perhaps do backing up   */
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 88 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 87);
/* end ofcode to find the next state, and perhaps do backing up      */
/*********************************************************************/
    return yy_is_jam ? 0 : yy_current_state;
}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
{
    register char *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if( yy_cp < yy_current_buffer->yy_ch_buf + 2 ) {
    /* need to shift things up to make room */
    /* +2 for EOB chars. */
        register int number_to_move = yy_n_chars + 2;
        register char *dest = &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
        register char *source = &yy_current_buffer->yy_ch_buf[number_to_move];

        while( source > yy_current_buffer->yy_ch_buf )
            *--dest = *--source;

        yy_cp += (int) (dest - source);
        yy_bp += (int) (dest - source);
        yy_current_buffer->yy_n_chars = yy_n_chars = yy_current_buffer->yy_buf_size;

        if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
            YY_FATAL_ERROR( "flex scanner push-back overflow" );
    }
    *--yy_cp = (char) c;

/****************************/
/* start of update yylineno */
/* end of update yylineno   */
/****************************/

    yytext_ptr = yy_bp;
    yy_hold_char = *yy_cp;
    yy_c_buf_p = yy_cp;
}


int yyFlexLexer::yyinput()
{
    int c;
    *yy_c_buf_p = yy_hold_char;

    if( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR ) {
    /* yy_c_buf_p now points to the character we want to return.
     * If this occurs *before* the EOB characters, then it's a
     * valid NUL; if not, then we've hit the end of the buffer.
     */
        if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
        /* This was really a NUL. */
            *yy_c_buf_p = '\0';

        else {
        /* need more input */
            int offset = yy_c_buf_p - yytext_ptr;
            ++yy_c_buf_p;

            switch ( yy_get_next_buffer() ) {
            case EOB_ACT_LAST_MATCH:
                /* This happens because yy_g_n_b()
                 * sees that we've accumulated a
                 * token and flags that we need to
                 * try matching the token before
                 * proceeding.  But for input(),
                 * there's no matching to consider.
                 * So convert the EOB_ACT_LAST_MATCH
                 * to EOB_ACT_END_OF_FILE.*/

                /* Reset buffer status. */
                yyrestart( yyin );

                /* fall through */

            case EOB_ACT_END_OF_FILE:
                {
                    if ( yywrap() )
                        return EOF;

                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;                    
                        
                #ifdef __cplusplus
                    return yyinput();
                #else
                    return input();
                #endif
                }

            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p = yytext_ptr + offset;
                break;
            }
        }
    }

    c = *(unsigned char *) yy_c_buf_p;  /* cast for 8-bit char's */
    *yy_c_buf_p = '\0'; /* preserve yytext */
    yy_hold_char = *++yy_c_buf_p;

/************************************/
/* start of update BOL and yylineno */
	yy_current_buffer->yy_at_bol = (c == '\n');
/* end of update BOL and yylineno   */
/************************************/

    return c;
}

void yyFlexLexer::yyrestart( std::istream* input_file )
{
    if ( ! yy_current_buffer )
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    if( yy_current_buffer == new_buffer )
        return;

    if( yy_current_buffer ) {
    /* Flush out information for old buffer. */
        *yy_c_buf_p = yy_hold_char;
        yy_current_buffer->yy_buf_pos = yy_c_buf_p;
        yy_current_buffer->yy_n_chars = yy_n_chars;
    }

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
}

void yyFlexLexer::yy_load_buffer_state()
{
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
}

YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
    if( ! b ) YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
    if( ! b->yy_ch_buf ) YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_is_our_buffer = 1;

    yy_init_buffer( b, file );

    return b;
}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    if ( ! b )
        return;

    if ( b == yy_current_buffer )
        yy_current_buffer = (YY_BUFFER_STATE) 0;

    if ( b->yy_is_our_buffer )
        yy_flex_free( (void *) b->yy_ch_buf );

    yy_flex_free( (void *) b );
}

extern "C" int isatty YY_PROTO(( int ));

void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )
{
    yy_flush_buffer( b );

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

    b->yy_is_interactive = 0;
}

void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    if ( ! b )
        return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.*/
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if( b == yy_current_buffer )
        yy_load_buffer_state();
}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif /* !YY_NO_SCAN_BYTES */


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
{
    if( yy_start_stack_ptr >= yy_start_stack_depth ) {
        yy_size_t new_size;

        yy_start_stack_depth += YY_START_STACK_INCR;
        new_size = yy_start_stack_depth * sizeof(int);

        if( !yy_start_stack )
            yy_start_stack = (int *) yy_flex_alloc( new_size );
        else
            yy_start_stack = (int *) yy_flex_realloc((void *)yy_start_stack, new_size);

        if( !yy_start_stack )
            YY_FATAL_ERROR("out of memory expanding start-condition stack" );
    }
    yy_start_stack[yy_start_stack_ptr++] = YY_START;
    BEGIN(new_state);
}
#endif /* !YY_NO_PUSH_STATE */


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
{
    if( --yy_start_stack_ptr < 0 )
        YY_FATAL_ERROR( "start-condition stack underflow" );
    BEGIN(yy_start_stack[yy_start_stack_ptr]);
}
#endif /* !YY_NO_POP_STATE */


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
{
	if( yy_start_stack_ptr == 0 )
		return YY_START;
    return yy_start_stack[yy_start_stack_ptr - 1];
}
#endif /* !YY_NO_TOP_STATE */

#ifndef YY_EXIT_FAILURE
    #define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError(yyconst char msg[])
{
    cerr << msg << '\n';
    exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */
#undef yyless
#define yyless(n) \
    do {\
        /* Undo effects of setting up yytext. */ \
        yytext[yyleng] = yy_hold_char; \
        yy_c_buf_p = yytext + n; \
        yy_hold_char = *yy_c_buf_p; \
        *yy_c_buf_p = '\0'; \
        yyleng = n; \
    } while ( 0 )


/* Internal utility routines. */
#ifndef yytext_ptr
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
{
    register int i;
    for ( i = 0; i < n; ++i )
        s1[i] = s2[i];
}
#endif /* yytext_ptr */

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen( yyconst char *s )
{
    register int n;
    for( n = 0; s[n]; ++n );

    return n;
}
#endif /* YY_NEED_STRLEN */


static void *yy_flex_alloc( yy_size_t size )
{
    return (void*)malloc( size );
}

static void *yy_flex_realloc( void *ptr, yy_size_t size )
{
/* The cast to (char *) in the following accommodates both
 * implementations that use char* generic pointers, and those
 * that use void* generic pointers.  It works with the latter
 * because both ANSI C and C++ allow castless assignment from
 * any pointer type to void*, and deal with argument conversions
 * as though doing an assignment.*/
    return (void *) realloc( (char *) ptr, size );
}

static void yy_flex_free( void *ptr )
{
    free( ptr );
}

#if YY_MAIN
    int main()
    {
        FlexLexer* lexer = new yyFlexLexer;
        while(lexer->yylex() != 0);
        delete lexer;
        return 0;
    }
#endif
#line 168 "C:\\work\\ape++\\src\\lexers\\LexerNSIS.L"

/*************************************************************************************/

int CSciLexer<yyFlexLexer>::StateToStyle(int nState) {
	switch(nState) {
		case INITIAL:		return STYLE_TEXT;
		case COMMENT:		
		case SLCOMMENT:		return STYLE_COMMENT;
		case STRING:		
		case STRING2:		
		case STRING3:		return STYLE_STRING;
		case PREPROCESSOR:	return STYLE_PREP;
	}
	return 0;
}