#define yyFlexLexer xhtml_FlexLexer
#define yywrap xhtml_wrap

#line 5 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: k:\\backup\\cvsroot/ape/lexer/Lexer.skl,v 1.1 2000/11/15 13:38:44 Basil_Burdo Exp $
 */
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#undef	yywrap

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
    #ifndef __cplusplus
        #define __cplusplus
    #endif
#endif


#ifdef __cplusplus
    #include <stdlib.h>
//  #include <unistd.h>
    class istream;

    /* Use prototypes in function declarations. */
    #define YY_USE_PROTOS
    /* The "const" storage-class-modifier is valid. */
    #define YY_USE_CONST
#else   /* ! __cplusplus */
    #if __STDC__
        #define YY_USE_PROTOS
        #define YY_USE_CONST
    #endif  /* __STDC__ */
#endif  /* ! __cplusplus */

#ifdef YY_USE_CONST
    #define yyconst const
#else
    #define yyconst
#endif

#ifdef YY_USE_PROTOS
    #define YY_PROTO(proto) proto
#else
    #define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.*/
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.*/
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.*/
#define YY_START			((yy_start - 1) / 2)
#define YYSTATE				YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *  if ( condition_holds )
 *      yyless( 5 );
 *  else
 *      do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        *yy_cp = yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).*/
typedef unsigned int yy_size_t;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
    { \
        if ( ! yy_current_buffer ) \
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
        yy_current_buffer->yy_is_interactive = is_interactive; \
    }

#define yy_set_bol(at_bol) \
    { \
        if ( ! yy_current_buffer ) \
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
        yy_current_buffer->yy_at_bol = at_bol; \
    }

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

/************************************************************************/
/* start of yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init  */
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int CSciLexer<yyFlexLexer>::yylex()
/* end of yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init    */
/************************************************************************/


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
    yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
    yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yy_c_buf_p = yy_cp;

/*********************************************************************************/
/* start of data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
static yyconst short int yy_accept[284] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      114,  112,  111,  112,  112,  112,  112,   26,   27,  112,
       21,   25,   28,  112,   21,   31,  112,   32,   33,  112,
       34,   10,    8,   11,  112,   19,    9,   12,  112,  112,
       63,   36,   64,  112,   38,   40,   37,   58,  112,   60,

       48,   39,   41,  112,   53,  112,  112,   57,  112,   62,
      112,   59,   61,   79,   72,   73,   77,   71,   75,   79,
       74,   78,   74,   76,   80,  112,  112,   87,  112,   89,
      112,   90,  112,   96,  112,   95,  112,  105,  100,  101,
      105,  103,  105,  102,  102,  104,  106,  112,  112,  108,
      112,  109,  110,  111,    0,    0,    0,    0,    5,    0,
        0,   30,   21,    0,    0,   22,   24,   29,   21,   31,
       33,   11,   20,   18,   19,    0,    0,    0,    0,   12,
       50,   52,   63,   64,   54,   56,   40,   49,   47,   48,
        0,    0,    0,    0,   41,   51,   53,   55,   57,   62,

       70,   69,   75,   74,   80,   81,   87,   86,   88,   86,
       82,   84,   86,   83,   96,   94,   94,   92,   91,   99,
       98,  103,   97,  102,  106,  107,  108,   35,    0,    0,
        3,    0,    6,    5,    5,    2,   23,   24,   22,   21,
       15,   17,   16,   13,   14,   44,   46,   45,   42,   43,
        0,    0,    0,    0,   84,    0,   93,    1,    3,    6,
        5,   21,    0,    0,   67,   68,   84,   85,    4,   21,
        0,   66,    0,    0,    0,    0,    7,    0,    0,    0,
        0,   65,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,   11,   12,
       12,   13,    8,    8,   14,    8,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   17,   17,   18,   19,   20,
       21,   22,   23,    8,   24,   25,   26,   27,   28,   25,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   31,   32,   29,   29,   29,   33,   34,   29,
       35,   36,   37,    8,   38,    8,   39,   39,   40,   25,

       41,   39,   42,   43,   44,   29,   29,   30,   45,   46,
       29,   47,   29,   46,   31,   48,   49,   46,   29,   50,
       34,   29,   51,    8,   52,    8,    1,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,

       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    2,    1,    1,    3,    1,    4,    1,    5,    1,
        1,    1,    1,    6,    3,    7,    7,    1,    1,    1,
        1,    1,    3,    7,    7,    7,    7,    7,    8,    8,
        8,    8,    8,    8,    1,    1,    1,    9,    7,    7,
        7,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1
    } ;

static yyconst short int yy_base[308] =
    {   0,
        0,    2,    4,   10,   24,    0,   13,   75,   79,   81,
       83,   85,  105,    0,  158,    0,  211,    0,   90,   92,
      264,    0,  317,    0,  368,  370,   94,   96,  372,  374,
       98,  376,  385,  389,  393,  395,  406,    0,  397,  399,
      457,  459,  461,  465,  470,  472,  474,  476,  512,    0,
      481,  483,  489,  491,  496,  563,  499,  565,  569,  571,
      799,  831,  831,  756,    0,  576,  744,  831,  831,  734,
        0,  577,  831,  725,  434,  831,  743,  831,  831,  742,
      831,  831,  831,    0,    0,  579,  831,    0,    8,  713,
        0,  831,  673,  369,  831,    0,  831,  831,    0,  831,

      588,  831,    0,  710,  831,  721,  708,  831,  719,  831,
      718,  831,  831,  831,  831,  831,  831,  475,  569,  704,
        0,  831,    0,  831,  831,  715,  701,  831,  712,  831,
      633,  831,  681,  831,  710,  454,  562,  831,  831,  831,
      574,  584,  690,    0,    0,  831,  831,  708,  695,  831,
      706,  831,  831,  831,  689,  607,  588,  705,    0,  608,
      684,  831,    0,  601,    0,  590,    0,  831,  668,  831,
      831,    0,    0,  831,  648,  656,  655,  649,  566,    0,
      831,  831,    0,  638,  831,  831,    0,    0,  831,  658,
      645,  641,  640,  577,    0,  831,  831,  831,  831,  831,

      831,  595,  624,    0,  831,  831,  831,  831,  831,  677,
      831,  662,    0,  831,  831,  633,  831,  831,  831,  831,
      831,  626,  831,    0,  831,  831,  831,  831,  636,  662,
        0,  671,    0,    0,  628,  831,    0,    0,  635,  640,
      831,  831,  831,  831,  831,  831,  831,  831,  831,  831,
      663,  626,  611,  609,  644,    0,  831,  831,    0,    0,
      612,   63,  623,  632,  831,  831,  831,  831,    0,  384,
      627,  831,  590,    9,  618,  388,  831,  610,  589,  559,
      535,  831,  831,  731,  734,  741,  745,  753,  757,  504,
      761,  765,  769,  500,  773,  776,  785,  788,  796,  804,

      808,  497,  813,   73,  817,  821,    2
    } ;

static yyconst short int yy_def[308] =
    {   0,
      284,  284,  284,  284,  283,    5,  284,  284,  284,  284,
      284,  284,  283,   13,  283,   15,  283,   17,  284,  284,
      283,   21,  283,   23,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  283,   37,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  283,   49,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      283,  283,  283,  283,  285,  286,  283,  283,  283,  283,
      287,  288,  283,  283,  287,  283,  283,  283,  283,  283,
      283,  283,  283,  289,  290,  283,  283,  291,  283,  283,
      292,  283,  283,  283,  283,  293,  283,  283,  294,  283,

      283,  283,  295,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      296,  283,  296,  283,  283,  283,  283,  283,  283,  283,
      297,  283,  297,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  298,  298,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  285,  286,  299,  300,  301,  286,
      283,  283,  287,  288,  302,  303,  303,  283,  287,  283,
      283,  289,  290,  283,  283,  283,  283,  283,  283,  291,
      283,  283,  292,  283,  283,  283,  293,  294,  283,  283,
      283,  283,  283,  283,  295,  283,  283,  283,  283,  283,

      283,  283,  283,  296,  283,  283,  283,  283,  283,  283,
      283,  283,  304,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  298,  283,  283,  283,  283,  299,  283,
      305,  300,  306,  301,  301,  283,  302,  303,  303,  287,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  307,  283,  283,  305,  306,
      301,  287,  283,  283,  283,  283,  283,  283,  301,  287,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,    0,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283
    } ;

static yyconst short int yy_nxt[885] =
    {   0,
      283,  283,   63,   64,   63,   64,   63,   64,  268,   65,
      276,   65,   63,   64,  277,   76,   77,   67,   78,   66,
      181,   66,  182,   67,   62,   62,   63,   64,   62,   68,
       62,   62,   62,   62,   69,   62,   62,   62,   70,   71,
       71,   62,   62,   62,   72,   73,   74,   71,   71,   71,
       71,   71,   71,   71,   75,   71,   71,   71,   62,   62,
       62,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   62,   62,   62,   76,   77,  256,
       78,   79,   80,   79,   80,   63,   64,   63,   64,   81,
      270,   81,   63,   64,   63,   64,  105,  106,  105,  106,

      108,  109,   66,  270,   66,   62,   62,   63,   64,   62,
       82,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   83,   62,   62,   62,   62,   62,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   62,
       62,   62,   62,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   62,   62,   62,   62,   62,
       63,   64,   62,   82,   85,   62,   62,   62,   62,   62,
       62,   62,   62,   86,   86,   62,   87,   62,   62,   62,
       62,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   62,   62,   62,   62,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   62,   62,
       62,   62,   62,   63,   64,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   89,   62,   62,   62,   62,
       90,   62,   62,   62,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   62,   62,   62,   62,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   92,   62,   93,   62,   62,   63,   64,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   94,   62,
       62,   95,   62,   62,   62,   62,   62,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   62,   62,

       62,   62,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   62,   97,   62,   62,   62,   63,
       64,   62,   98,   99,   62,   62,   62,  100,   62,   62,
       62,   62,  101,  101,   62,  102,   62,   62,   62,   62,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,   62,   62,   62,   62,  103,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,   62,   97,   62,
       63,   64,   63,   64,   63,   64,   63,   64,  108,  109,
      104,  185,  104,  186,  107,  273,  107,  110,  111,  276,
      112,  110,  111,  277,  112,  110,  111,  110,  111,  125,

      126,  125,  126,  113,  274,  113,   62,   62,   63,   64,
      114,  115,  114,  114,  114,  114,  116,  117,  114,  114,
      118,  119,  119,  114,  114,  120,  114,  114,  114,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      122,  114,  122,  123,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  124,  124,   62,   63,
       64,   63,   64,  128,  129,  169,  130,  128,  129,  127,
      130,  127,  128,  129,  128,  129,  134,  135,  134,  135,
      132,  169,  132,   63,   64,   63,   64,  201,  136,  202,
      136,  147,  148,  147,  148,  216,  131,  217,   63,   64,

      131,  150,  151,  237,  152,  133,  188,  133,  149,  137,
      173,  137,   62,   62,   63,   64,  138,  139,  138,  138,
      138,  138,  140,  138,  138,  138,  141,  142,  142,  138,
      138,  138,  138,  138,  143,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  138,  138,  138,  145,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  146,  146,   62,   63,   64,  150,  151,  282,
      152,  150,  151,  150,  151,  149,  218,  156,  164,  153,
      157,  153,  281,  165,  203,  203,  220,  174,  221,  229,
      158,  273,  166,  166,  175,  175,  189,  219,  160,  222,

      222,  230,  164,  190,  190,  239,  239,  165,  156,  156,
      274,  283,  283,  244,  251,  245,  166,  166,  176,  177,
      280,  283,  283,  178,  249,  179,  250,  191,  192,  283,
      283,  252,  193,  279,  194,  209,  210,  229,  211,  203,
      203,  222,  222,  211,  278,  253,  254,  211,  212,  283,
      239,  239,  275,  272,  235,  211,  174,  271,  269,  267,
      266,  265,  264,  175,  175,  213,  189,  263,  211,  262,
      261,  211,  232,  190,  190,  258,  257,  255,  211,  209,
      211,  214,  213,  283,  248,  247,  211,  176,  177,  246,
      184,  211,  178,  243,  179,  211,  212,  191,  192,  242,

      241,  240,  193,  211,  194,  236,  232,  228,  227,  226,
      225,  223,  215,  213,  207,  206,  211,  205,  158,  211,
      200,  199,  198,  197,  196,  184,  211,  158,  211,  214,
      213,   62,   62,   62,   62,   62,   62,   62,   62,   62,
      155,  155,  159,  159,  171,  170,  168,  159,  159,  159,
      163,  163,  163,  163,  167,  162,  167,  161,  154,  167,
      167,  167,  172,  172,  172,  172,  180,  180,  180,  180,
      183,  183,  183,  183,  187,  187,  187,  187,  195,  195,
      195,  195,  204,  204,  204,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  224,  224,  224,  231,  283,  283,

      283,  231,  231,  231,  231,  233,  283,  283,  283,  283,
      233,  233,  233,  234,  234,  234,  234,  238,  283,  238,
      238,  238,  259,  259,  259,  259,  260,  260,  260,  260,
       61,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283
    } ;

static yyconst short int yy_chk[885] =
    {   0,
        0,    0,    1,    1,    2,    2,    3,    3,  307,    1,
      274,    2,    4,    4,  274,    7,    7,    3,    7,    1,
       89,    2,   89,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    8,    8,  304,
        8,    9,    9,   10,   10,   11,   11,   12,   12,    9,
      262,   10,   19,   19,   20,   20,   27,   27,   28,   28,

       31,   31,   11,  262,   12,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,

       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       25,   25,   26,   26,   29,   29,   30,   30,   32,   32,
       25,   94,   26,   94,   29,  270,   30,   33,   33,  276,
       33,   34,   34,  276,   34,   35,   35,   36,   36,   39,

       39,   40,   40,   35,  270,   36,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   41,
       41,   42,   42,   43,   43,   75,   43,   44,   44,   41,
       44,   42,   45,   45,   46,   46,   47,   47,   48,   48,
       45,   75,   46,   51,   51,   52,   52,  118,   47,  118,
       48,   53,   53,   54,   54,  136,   43,  136,   55,   55,

       44,   57,   57,  302,   57,   45,  294,   46,   55,   47,
      290,   48,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   56,   56,   58,   58,  281,
       58,   59,   59,   60,   60,   56,  137,   66,   72,   59,
       66,   60,  280,   72,  119,  119,  141,   86,  141,  157,
       66,  273,   72,   72,   86,   86,  101,  137,   66,  142,

      142,  157,  164,  101,  101,  166,  166,  164,  156,  160,
      273,  156,  160,  179,  202,  179,  164,  164,   86,   86,
      279,  156,  160,   86,  194,   86,  194,  101,  101,  156,
      160,  202,  101,  278,  101,  131,  131,  229,  131,  203,
      203,  222,  222,  131,  275,  202,  202,  131,  131,  229,
      239,  239,  271,  264,  160,  131,  175,  263,  261,  255,
      254,  253,  252,  175,  175,  131,  190,  251,  131,  240,
      235,  131,  232,  190,  190,  230,  216,  212,  131,  210,
      131,  131,  131,  133,  193,  192,  133,  175,  175,  191,
      184,  133,  175,  178,  175,  133,  133,  190,  190,  177,

      176,  169,  190,  133,  190,  161,  158,  155,  151,  149,
      148,  143,  135,  133,  129,  127,  133,  126,  120,  133,
      111,  109,  107,  106,  104,   93,  133,   90,  133,  133,
      133,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      285,  285,  286,  286,   80,   77,   74,  286,  286,  286,
      287,  287,  287,  287,  288,   70,  288,   67,   64,  288,
      288,  288,  289,  289,  289,  289,  291,  291,  291,  291,
      292,  292,  292,  292,  293,  293,  293,  293,  295,  295,
      295,  295,  296,  296,  296,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  298,  298,  298,  299,   61,    0,

        0,  299,  299,  299,  299,  300,    0,    0,    0,    0,
      300,  300,  300,  301,  301,  301,  301,  303,    0,  303,
      303,  303,  305,  305,  305,  305,  306,  306,  306,  306,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
#define INITIAL 0
#line 2 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
#include "LexBase.h"
#include "stylesXHTML.h"
// without "', esc - []-\/
#define COMMENT 1
#define INTAG 2
#define STRING 3
#define STRING2 4
#define UNDEF 5
 
// intag CSS states
#define INTAG_CSS_ATTR 6
#define INTAG_CSS_VALUE 7

// CSS states
#define CSS 8
#define CSS_SELECTOR 9
#define CSS_ATTR 10
#define CSS_VALUE 11
#define CSS_COMMENT 12
#define CSS_SL_COMMENT 13
#define CSS_COMMENTA 14
#define CSS_SL_COMMENTA 15
#define CSS_STRING 16
#define CSS_CHAR 17

// JS States
#define JS 18
#define JS_SLCOMMENT 19
#define JS_COMMENT 20
#define JS_STRING 21
#define JS_CHAR 22
#define JS_REGEXP 23

// PHP States
#define PHP 24
#define PHP_KEYWORD 25
#define PHP_SLCOMMENT 26
#define PHP_COMMENT 27
#define PHP_STRING 28
#define PHP_CHAR 29

#line 36 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"

bool isHTMLKeyword( const char* pText  ) 
{ 
	static CKeywordsIC htmlKW("&nbsp; &amp; &lt; &gt; &quote; &apos; &quot; &curren; &middot;",true);
	return htmlKW.is(pText); 
}

bool isCssKeyword( const char* text );
bool isCssValue( const char* text );

extern bool g_isJSRegExp;
bool isJSKeyword( const char* szKW );

bool isPHPKeyword( const char* szKW )
{
	static CKeywords php("if else elseif define defined function return echo switch case default break foreach for substr strtolower strtoupper strlen empty true false global importClass class_exists new exit abstract class extends public protected private static array is_array",true);
	return php.is(szKW); 
}

#line 628 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.cpp"
/* end of data tables for the DFA and the user's section 1 definitions go here   */
/*********************************************************************************/


#ifndef yytext_ptr
    static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
    static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
    static int yy_start_stack_ptr = 0;
    static int yy_start_stack_depth = 0;
    static int *yy_start_stack = 0;
    #ifndef YY_NO_PUSH_STATE
        static void yy_push_state YY_PROTO(( int new_state ));
    #endif
    #ifndef YY_NO_POP_STATE
        static void yy_pop_state YY_PROTO(( void ));
    #endif
    #ifndef YY_NO_TOP_STATE
        static int yy_top_state YY_PROTO(( void ));
    #endif
#else
    #define YY_NO_PUSH_STATE    1
    #define YY_NO_POP_STATE     1
    #define YY_NO_TOP_STATE     1
#endif

#ifdef YY_MALLOC_DECL
    YY_MALLOC_DECL
#else
    #if __STDC__
        #ifndef __cplusplus
            #include <stdlib.h>
        #endif
    #else
        /* Just try to get by without declaring the routines.  This will fail
         * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
         * or sizeof(void*) != sizeof(int).
         */
    #endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
    #define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
    #define ECHO LexerOutput( yytext, yyleng )
#endif /* !ECHO */

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
    #define YY_INPUT(buf,result,max_size) \
        if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
            YY_FATAL_ERROR( "input in flex scanner failed" );
#endif /* !YY_INPUT */

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.*/
#ifndef yyterminate
    #define yyterminate() return YY_NULL
#endif /* !yyterminate */

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
    #define YY_START_STACK_INCR 25
#endif /* !YY_START_STACK_INCR */

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
    #define YY_FATAL_ERROR(msg) LexerError( msg )
#endif /* !YY_FATAL_ERROR */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
    #define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.*/
#ifndef YY_USER_ACTION
    #define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
    #define YY_BREAK    break;
#endif

/************************************************************************/
/* start of YY_RULE_SETUP definition                                    */
#define YY_RULE_SETUP \
	YY_USER_ACTION
/* end of YY_RULE_SETUP definition                                      */
/************************************************************************/

YY_DECL
{
    register yy_state_type yy_current_state;
    register char *yy_cp, *yy_bp;
    register int yy_act;

/************************************************************************/
/* start of user's declarations                                         */
#line 57 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"

 /*************************************************************************************/

	int after_tag = INITIAL; // UNDEF, INITIAL or CSS or SCR_JS

 /* ========================================================================================
 // comment
 // =======================================================================================*/

#line 758 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.cpp"
/* end of user's declarations                                           */
/************************************************************************/

    if( yy_init ) {
        yy_init = 0;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif /* YY_USER_INIT */

        if( !yy_start )
            yy_start = 1;   /* first start state */

        if( !yyin )
            yyin = &cin;

        if( !yyout )
            yyout = &cout;

        if( !yy_current_buffer )
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

        yy_load_buffer_state();
    }

    while( 1 )      /* loops until end-of-file is reached */
    {
/************************************************************************/
/* start of yymore()-related code                                       */
/* end of yymore()-related code                                         */
/************************************************************************/
        
        yy_cp = yy_c_buf_p;

        *yy_cp = yy_hold_char; /* Support of yytext. */

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run. */
        yy_bp = yy_cp;

/************************************************************************/
/* start of code to set up and find next match                          */
		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 284 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 831 );
/* end of code to set up and find next match                            */
/************************************************************************/

yy_find_action:

/************************************************************************/
/* start of code to find the action number                              */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}
/* end of code to find the action number                                */
/************************************************************************/

        YY_DO_BEFORE_ACTION;

/************************************************************************/
/* start of code for yylineno update                                    */
/* end if code for yylineno update                                      */
/************************************************************************/

do_action:  /* This label is used only to access EOF actions. */

/************************************************************************/
/* start of debug code                                                  */
/* end of debug code                                                    */
/************************************************************************/
        switch ( yy_act ) { /* beginning of action switch */
/************************************************************************/
/* start of actions code                                                */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;


case 1:
YY_RULE_SETUP
#line 67 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(COMMENT); SetStyle(); levelIncrease();
	YY_BREAK


case 2:
YY_RULE_SETUP
#line 70 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(INITIAL); levelDecrease();
	YY_BREAK

case 3:
YY_RULE_SETUP
#line 73 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
{
		SetStyle( MatchStart(), MatchStart()+2, STYLE_SYMBOL );
		SetStyle( MatchStart()+2, MatchEnd(), STYLE_TAG_NAME );
		BEGIN(INTAG); 
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 79 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
{
	BEGIN(PHP); SetStyle();
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 83 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
{
		char* pText = yytext;
		pText++;
		if( *pText=='!' ) pText++;
		BEGIN(INTAG); 
		SetStyle( MatchStart(), MatchStart()+(pText-yytext), STYLE_SYMBOL );
		SetStyle( MatchStart()+(pText-yytext), MatchEnd(), STYLE_TAG_NAME );
		levelIncrease();
		after_tag = INITIAL;
		if( !strcmpi(pText,"script") )
			after_tag = JS;
		else
		if( !strcmpi(pText,"style") )
			after_tag = CSS;
	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 99 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
{
		char* pText = yytext;
		pText += 2;
		BEGIN(INTAG); 
		SetStyle( MatchStart(), MatchStart()+(pText-yytext), STYLE_SYMBOL );
		SetStyle( MatchStart()+(pText-yytext), MatchEnd(), STYLE_TAG_NAME );
		levelDecrease();
		after_tag = INITIAL;
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 109 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
{
									SetStyle(MatchStart(), MatchStart()+5, STYLE_TAG_ATTR); 
									SetStyle(MatchStart()+5, MatchEnd()-1, STYLE_SYMBOL); 
									SetStyle(MatchEnd()-1, MatchEnd(), STYLE_CSS_SYMBOL); 
									BEGIN(INTAG_CSS_ATTR);
								}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 115 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_CSS_SYMBOL); BEGIN(INTAG_CSS_VALUE);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 116 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_CSS_SYMBOL); BEGIN(INTAG_CSS_ATTR);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 117 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_CSS_SYMBOL); BEGIN(INTAG);
	YY_BREAK

case 11:
YY_RULE_SETUP
#line 120 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
if(isCssKeyword(yytext)) SetStyle(STYLE_CSS_ATTR_KW); else SetStyle();
	YY_BREAK


case 12:
YY_RULE_SETUP
#line 123 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
if(isCssValue(yytext)) SetStyle(STYLE_CSS_VAL_KW); else SetStyle();
	YY_BREAK


case 13:
#line 127 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 14:
#line 128 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 15:
#line 129 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 16:
#line 130 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 17:
#line 131 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 18:
#line 132 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 19:
#line 133 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 20:
YY_RULE_SETUP
#line 133 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_CSS_NUMBER);
	YY_BREAK


case 21:
YY_RULE_SETUP
#line 137 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle( STYLE_TAG_ATTR );
	YY_BREAK
case 22:
#line 139 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 23:
YY_RULE_SETUP
#line 139 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
{
		SetStyle( MatchStart(), MatchStart()+1, STYLE_SYMBOL); 
		SetStyle( MatchStart()+1, MatchEnd(), STYLE_TAG_NUMBER);
	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 143 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
{
		SetStyle( MatchStart(), MatchStart()+1, STYLE_SYMBOL); 
		SetStyle( MatchStart()+1, MatchEnd(), STYLE_TAG_TEXT);
	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 147 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_SYMBOL);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 148 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(STRING); SetStyle();
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 149 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(STRING2);	SetStyle();
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 150 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_SYMBOL); BEGIN(after_tag); 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 151 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_SYMBOL); BEGIN(after_tag); levelDecrease();
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 152 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_SYMBOL); BEGIN(after_tag); levelDecrease();
	YY_BREAK


case 31:
YY_RULE_SETUP
#line 156 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_STRING_UNQ); BEGIN(after_tag);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 157 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(INTAG);
	YY_BREAK


case 33:
YY_RULE_SETUP
#line 160 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_STRING_UNQ); BEGIN(after_tag);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 161 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(INTAG);
	YY_BREAK


case 35:
YY_RULE_SETUP
#line 165 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
if( isHTMLKeyword(yytext) ) SetStyle(STYLE_KW); else SetStyle();
	YY_BREAK

/* ========================================================================================
 // CSS
 // ========================================================================================*/
case 36:
YY_RULE_SETUP
#line 172 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_CSS_SYMBOL); BEGIN(CSS_ATTR); levelIncrease();
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 173 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_CSS_SYMBOL); BEGIN(CSS); levelDecrease();
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 174 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_CSS_SYMBOL); BEGIN(CSS_VALUE);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 175 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_CSS_SYMBOL); BEGIN(CSS_ATTR);
	YY_BREAK

case 40:
YY_RULE_SETUP
#line 178 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
if(isCssKeyword(yytext)) SetStyle(STYLE_CSS_ATTR_KW); else SetStyle();
	YY_BREAK


case 41:
YY_RULE_SETUP
#line 181 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
if(isCssValue(yytext)) SetStyle(STYLE_CSS_VAL_KW); else SetStyle();
	YY_BREAK


case 42:
#line 185 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 43:
#line 186 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 44:
#line 187 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 45:
#line 188 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 46:
#line 189 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 47:
#line 190 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 48:
#line 191 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 49:
YY_RULE_SETUP
#line 191 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_CSS_NUMBER);
	YY_BREAK

case 50:
YY_RULE_SETUP
#line 194 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(CSS_COMMENT);   SetStyle(); levelIncrease();
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 195 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle();	BEGIN(CSS); levelDecrease();
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 197 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(CSS_SL_COMMENT); SetStyle();
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 198 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(CSS); SetStyle();
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 200 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(CSS_COMMENTA);   SetStyle(); levelIncrease();
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 201 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle();	BEGIN(CSS_ATTR); levelDecrease();
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 203 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(CSS_SL_COMMENTA); SetStyle();
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 204 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(CSS_ATTR); SetStyle();
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 206 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(CSS_STRING);	  SetStyle();
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 207 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(CSS_VALUE);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 209 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(CSS_CHAR);	  SetStyle();
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 210 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(CSS_VALUE);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 212 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_CSS_UNQ); BEGIN(CSS);
	YY_BREAK

case 63:
YY_RULE_SETUP
#line 215 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_CSS_SELECTOR);
	YY_BREAK
/* invalid chars - all second part of the ASCII table */
case 64:
YY_RULE_SETUP
#line 218 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(IStyler::styleInvalidText);
	YY_BREAK

/* ========================================================================================
 // JS
 // ========================================================================================*/

case 65:
YY_RULE_SETUP
#line 226 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(JS_SLCOMMENT); SetStyle(); levelIncrease(); 
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 227 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(JS_SLCOMMENT); SetStyle(); levelDecrease(); 
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 229 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(JS_SLCOMMENT); SetStyle(); levelIncrease();
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 230 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(JS_SLCOMMENT); SetStyle(); levelDecrease();
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 232 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(JS_SLCOMMENT); SetStyle();
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 233 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(JS_COMMENT); SetStyle(); levelIncrease();
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 234 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
if( g_isJSRegExp ) { BEGIN(JS_REGEXP); SetStyle(); } else SetStyle(STYLE_JS_SYMBOL);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 235 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(JS_STRING); SetStyle();
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 236 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(JS_CHAR); SetStyle();
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 238 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
if( isJSKeyword(yytext) ) SetStyle( STYLE_JS_KW ); else SetStyle();
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 239 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_JS_NUMBER);
	YY_BREAK
/* folding */
case 76:
YY_RULE_SETUP
#line 242 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_JS_SYMBOL);	if( *yytext=='{' ) levelIncrease(); else levelDecrease();
	YY_BREAK
/* folding */
case 77:
YY_RULE_SETUP
#line 245 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_JS_SYMBOL);	if( *yytext=='(' ) levelIncrease(); else { levelDecrease(); g_isJSRegExp=false; }
	YY_BREAK
/* folding */
case 78:
YY_RULE_SETUP
#line 248 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_JS_SYMBOL);		if( *yytext=='[' ) levelIncrease(); else levelDecrease();
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 250 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_JS_SYMBOL);
	YY_BREAK


case 80:
YY_RULE_SETUP
#line 254 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(JS); SetStyle();
	YY_BREAK


case 81:
YY_RULE_SETUP
#line 257 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(JS); levelDecrease();
	YY_BREAK


/*escaped symbols*/
case 82:
#line 262 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 83:
#line 263 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 84:
#line 264 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 85:
YY_RULE_SETUP
#line 264 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle();
	YY_BREAK
/*invalid escaped symbol*/
case 86:
YY_RULE_SETUP
#line 267 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(IStyler::styleInvalidText);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 269 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_JS_UNQ); BEGIN(JS);
	YY_BREAK


case 88:
YY_RULE_SETUP
#line 272 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(JS);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 273 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(JS);
	YY_BREAK


case 90:
YY_RULE_SETUP
#line 276 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(JS);
	YY_BREAK


case 91:
YY_RULE_SETUP
#line 279 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle();  // "\\" escaped \
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 280 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle();
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 281 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle( MatchStart(), MatchEnd()-2, STYLE_JS_REGEXP ); SetStyle( MatchEnd()-2, MatchEnd(), STYLE_JS_REGEXP_BOLD ); BEGIN(JS);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 282 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle( MatchStart(), MatchEnd()-1, STYLE_JS_REGEXP ); SetStyle( MatchEnd()-1, MatchEnd(), STYLE_JS_REGEXP_BOLD ); BEGIN(JS);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 283 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(JS);
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 284 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_JS_UNQ); BEGIN(JS);
	YY_BREAK

/* ========================================================================================
 // PHP
 // ========================================================================================*/

case 97:
YY_RULE_SETUP
#line 292 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(INITIAL); SetStyle();
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 293 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(PHP_SLCOMMENT); SetStyle();
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 294 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(PHP_COMMENT); SetStyle(); levelIncrease();
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 295 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(PHP_STRING); SetStyle();
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 296 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(PHP_CHAR); SetStyle();
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 297 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
if( isPHPKeyword(yytext) ) SetStyle( STYLE_PHP_KW ); else SetStyle();
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 298 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_PHP_NUMBER);
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 299 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_PHP_SYMBOL); if( *yytext=='{' ) levelIncrease(); else levelDecrease();
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 300 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_PHP_SYMBOL);
	YY_BREAK


case 106:
YY_RULE_SETUP
#line 304 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
BEGIN(PHP); SetStyle();
	YY_BREAK


case 107:
YY_RULE_SETUP
#line 307 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(PHP); levelDecrease();
	YY_BREAK


case 108:
YY_RULE_SETUP
#line 310 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(STYLE_PHP_UNQ); BEGIN(PHP);
	YY_BREAK


case 109:
YY_RULE_SETUP
#line 313 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(PHP);
	YY_BREAK


case 110:
YY_RULE_SETUP
#line 316 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle(); BEGIN(PHP);
	YY_BREAK

/* ========================================================================================
 // default rule
 // ========================================================================================*/

case 111:
#line 325 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
case 112:
YY_RULE_SETUP
#line 325 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
SetStyle();
	YY_BREAK

case 113:
YY_RULE_SETUP
#line 328 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"
ECHO;
	YY_BREAK
#line 1480 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(INTAG):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(STRING2):
case YY_STATE_EOF(UNDEF):
case YY_STATE_EOF(INTAG_CSS_ATTR):
case YY_STATE_EOF(INTAG_CSS_VALUE):
case YY_STATE_EOF(CSS):
case YY_STATE_EOF(CSS_SELECTOR):
case YY_STATE_EOF(CSS_ATTR):
case YY_STATE_EOF(CSS_VALUE):
case YY_STATE_EOF(CSS_COMMENT):
case YY_STATE_EOF(CSS_SL_COMMENT):
case YY_STATE_EOF(CSS_COMMENTA):
case YY_STATE_EOF(CSS_SL_COMMENTA):
case YY_STATE_EOF(CSS_STRING):
case YY_STATE_EOF(CSS_CHAR):
case YY_STATE_EOF(JS):
case YY_STATE_EOF(JS_SLCOMMENT):
case YY_STATE_EOF(JS_COMMENT):
case YY_STATE_EOF(JS_STRING):
case YY_STATE_EOF(JS_CHAR):
case YY_STATE_EOF(JS_REGEXP):
case YY_STATE_EOF(PHP):
case YY_STATE_EOF(PHP_KEYWORD):
case YY_STATE_EOF(PHP_SLCOMMENT):
case YY_STATE_EOF(PHP_COMMENT):
case YY_STATE_EOF(PHP_STRING):
case YY_STATE_EOF(PHP_CHAR):
	yyterminate();
/* end of actions code                                                  */
/************************************************************************/
        case YY_END_OF_BUFFER: {
            /* Amount of text matched not including the EOB char. */
            int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;
    
            /* Undo the effects of YY_DO_BEFORE_ACTION. */
            *yy_cp = yy_hold_char;
            YY_RESTORE_YY_MORE_OFFSET

            if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
            {/* We're scanning a new file or input source.  It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex().  If so, then we have to assure
             * consistency between yy_current_buffer and our
             * globals.  Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.*/
                yy_n_chars = yy_current_buffer->yy_n_chars;
                yy_current_buffer->yy_input_file = yyin;
                yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
            }

            /* Note that here we test for yy_c_buf_p "<=" to the position
             * of the first EOB in the buffer, since yy_c_buf_p will
             * already have been incremented past the NUL character
             * (since all states make transitions on EOB to the
             * end-of-buffer state).  Contrast this with the test
             * in input().*/
            if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            {/* This was really a NUL. */
                yy_state_type yy_next_state;

                yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state();

            /* Okay, we're now positioned to make the NUL
             * transition.  We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).*/

                yy_next_state = yy_try_NUL_trans( yy_current_state );

                yy_bp = yytext_ptr + YY_MORE_ADJ;

                if( yy_next_state )
                {/* Consume the NUL. */
                    yy_cp = ++yy_c_buf_p;
                    yy_current_state = yy_next_state;
                    goto yy_match;
                } else {
/************************************************************************/
/* start ofcode to do back-up for compressed tables and set up yy_cp    */              
				yy_cp = yy_c_buf_p;
/* end if code to do back-up for compressed tables and set up yy_cp     */              
/************************************************************************/
                    goto yy_find_action;
                }
            } else
            switch ( yy_get_next_buffer() ) {
            case EOB_ACT_END_OF_FILE: {
                yy_did_buffer_switch_on_eof = 0;
                if( yywrap() ) {
                /* Note: because we've taken care in
                 * yy_get_next_buffer() to have set up
                 * yytext, we can now set up
                 * yy_c_buf_p so that if some total
                 * hoser (like flex itself) wants to
                 * call the scanner after we return the
                 * YY_NULL, it'll still work - another
                 * YY_NULL will get returned.*/
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
                    yy_act = YY_STATE_EOF(YY_START);
                    goto do_action;
                } else {
                    if( !yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
                }
                break;}
            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;
                yy_current_state = yy_get_previous_state();
                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_match;
            case EOB_ACT_LAST_MATCH:
                yy_c_buf_p = &yy_current_buffer->yy_ch_buf[yy_n_chars];
                yy_current_state = yy_get_previous_state();
                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_find_action;
            }
            break;}
        default:
            YY_FATAL_ERROR("fatal flex scanner internal error--no action found" );
        } /* end of action switch */
    } /* end of scanning one token */
} /* end of yylex */
#undef YY_DECL

yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
    yyin            = arg_yyin;
    yyout           = arg_yyout;
    yy_c_buf_p      = 0;
    yy_init         = 1;
    yy_start        = 0;
    yy_flex_debug   = 0;
    yylineno        = 1;    // this will only get updated if %option yylineno

    yy_did_buffer_switch_on_eof					= 0;

    yy_looking_for_trail_begin                  = 0;
    yy_more_flag                                = 0;
    yy_more_len                                 = 0;
    yy_more_offset = yy_prev_more_offset        = 0;

    yy_start_stack_ptr = yy_start_stack_depth   = 0;
    yy_start_stack                              = 0;

    yy_current_buffer                           = 0;

#ifdef YY_USES_REJECT
    yy_state_buf                                = new yy_state_type[YY_BUF_SIZE + 2];
#else
    yy_state_buf                                = 0;
#endif
}

yyFlexLexer::~yyFlexLexer()
{
    delete yy_state_buf;
    yy_delete_buffer( yy_current_buffer );
}

void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
    if ( new_in ) {
        yy_delete_buffer( yy_current_buffer );
        yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
    }

    if ( new_out )
        yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif /* !YY_INTERACTIVE */
{
    if( yyin->eof() || yyin->fail() )
        return 0;

#ifdef YY_INTERACTIVE
    yyin->get( buf[0] );
    if( yyin->eof() )
        return 0;
    if( yyin->bad() )
        return -1;
    return 1;
#else  /* YY_INTERACTIVE */
    (void) yyin->read( buf, max_size );
    if( yyin->bad() )
        return -1;
    else
        return yyin->gcount();
#endif /* !YY_INTERACTIVE */
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
    (void) yyout->write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *  EOB_ACT_LAST_MATCH -
 *  EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *  EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    register char *dest = yy_current_buffer->yy_ch_buf;
    register char *source = yytext_ptr;
    register int number_to_move, i;
    int ret_val;

    if( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
        YY_FATAL_ERROR("fatal flex scanner internal error--end of buffer missed" );

    if( yy_current_buffer->yy_fill_buffer == 0 )
    { /* Don't try to fill the buffer, so this is an EOF. */
        if( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 ) {
        /* We matched a single character, the EOB, so
         *  treat this as a final EOF.
         */
            return EOB_ACT_END_OF_FILE;
        } else {
        /* We matched some text prior to the EOB, first
         * process it.
         */
            return EOB_ACT_LAST_MATCH;
        }
    }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

    for( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

    if( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
    /* don't do the read, it's not guaranteed to return an EOF,
     * just force an EOF
     */
        yy_current_buffer->yy_n_chars = yy_n_chars = 0;

    else {
        int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;
        while ( num_to_read <= 0 ) {
            /* Not enough room in the buffer - grow it. */
        #ifdef YY_USES_REJECT
            YY_FATAL_ERROR("input buffer overflow, can't enlarge buffer because scanner uses REJECT");
        #else
            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = yy_current_buffer;

            int yy_c_buf_p_offset = (int)(yy_c_buf_p - b->yy_ch_buf);

            if( b->yy_is_our_buffer ) {
                int new_size = b->yy_buf_size * 2;
                if ( new_size <= 0 )
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char *)
                    /* Include room in for 2 EOB chars. */
                    yy_flex_realloc( (void *) b->yy_ch_buf, b->yy_buf_size + 2 );
            } else /* Can't grow it, we don't own it. */
                b->yy_ch_buf = 0;

            if ( ! b->yy_ch_buf )
                YY_FATAL_ERROR("fatal error - scanner input buffer overflow" );

            yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];
            num_to_read = yy_current_buffer->yy_buf_size -
                        number_to_move - 1;
        #endif
        }

        if( num_to_read > YY_READ_BUF_SIZE )
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]), yy_n_chars, num_to_read );
        yy_current_buffer->yy_n_chars = yy_n_chars;
    }

    if( yy_n_chars == 0 ) {
        if( number_to_move == YY_MORE_ADJ ) {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart( yyin );
        } else {
            ret_val = EOB_ACT_LAST_MATCH;
            yy_current_buffer->yy_buffer_status = YY_BUFFER_EOF_PENDING;
        }
    } else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

    return ret_val;
}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
{
    register yy_state_type yy_current_state;
    register char *yy_cp;
/*********************************************************************/
/* start of code to get the start state into yy_current_state        */
	yy_current_state = yy_start;
/* end of start of code to get the start state into yy_current_state */
/*********************************************************************/

    for( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
    {
/*********************************************************************/
/* start of code to find the next state                              */     
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 284 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
/* end of code to find the next state                                */     
/*********************************************************************/
    }

    return yy_current_state;
}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *  next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
    register int yy_is_jam;
/*********************************************************************/
/* start of code to find the next state, and perhaps do backing up   */
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 284 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 283);
/* end ofcode to find the next state, and perhaps do backing up      */
/*********************************************************************/
    return yy_is_jam ? 0 : yy_current_state;
}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
{
    register char *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if( yy_cp < yy_current_buffer->yy_ch_buf + 2 ) {
    /* need to shift things up to make room */
    /* +2 for EOB chars. */
        register int number_to_move = yy_n_chars + 2;
        register char *dest = &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
        register char *source = &yy_current_buffer->yy_ch_buf[number_to_move];

        while( source > yy_current_buffer->yy_ch_buf )
            *--dest = *--source;

        yy_cp += (int) (dest - source);
        yy_bp += (int) (dest - source);
        yy_current_buffer->yy_n_chars = yy_n_chars = yy_current_buffer->yy_buf_size;

        if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
            YY_FATAL_ERROR( "flex scanner push-back overflow" );
    }
    *--yy_cp = (char) c;

/****************************/
/* start of update yylineno */
/* end of update yylineno   */
/****************************/

    yytext_ptr = yy_bp;
    yy_hold_char = *yy_cp;
    yy_c_buf_p = yy_cp;
}


int yyFlexLexer::yyinput()
{
    int c;
    *yy_c_buf_p = yy_hold_char;

    if( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR ) {
    /* yy_c_buf_p now points to the character we want to return.
     * If this occurs *before* the EOB characters, then it's a
     * valid NUL; if not, then we've hit the end of the buffer.
     */
        if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
        /* This was really a NUL. */
            *yy_c_buf_p = '\0';

        else {
        /* need more input */
            int offset = yy_c_buf_p - yytext_ptr;
            ++yy_c_buf_p;

            switch ( yy_get_next_buffer() ) {
            case EOB_ACT_LAST_MATCH:
                /* This happens because yy_g_n_b()
                 * sees that we've accumulated a
                 * token and flags that we need to
                 * try matching the token before
                 * proceeding.  But for input(),
                 * there's no matching to consider.
                 * So convert the EOB_ACT_LAST_MATCH
                 * to EOB_ACT_END_OF_FILE.*/

                /* Reset buffer status. */
                yyrestart( yyin );

                /* fall through */

            case EOB_ACT_END_OF_FILE:
                {
                    if ( yywrap() )
                        return EOF;

                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;                    
                        
                #ifdef __cplusplus
                    return yyinput();
                #else
                    return input();
                #endif
                }

            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p = yytext_ptr + offset;
                break;
            }
        }
    }

    c = *(unsigned char *) yy_c_buf_p;  /* cast for 8-bit char's */
    *yy_c_buf_p = '\0'; /* preserve yytext */
    yy_hold_char = *++yy_c_buf_p;

/************************************/
/* start of update BOL and yylineno */
/* end of update BOL and yylineno   */
/************************************/

    return c;
}

void yyFlexLexer::yyrestart( std::istream* input_file )
{
    if ( ! yy_current_buffer )
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    if( yy_current_buffer == new_buffer )
        return;

    if( yy_current_buffer ) {
    /* Flush out information for old buffer. */
        *yy_c_buf_p = yy_hold_char;
        yy_current_buffer->yy_buf_pos = yy_c_buf_p;
        yy_current_buffer->yy_n_chars = yy_n_chars;
    }

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
}

void yyFlexLexer::yy_load_buffer_state()
{
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
}

YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
    if( ! b ) YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
    if( ! b->yy_ch_buf ) YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_is_our_buffer = 1;

    yy_init_buffer( b, file );

    return b;
}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    if ( ! b )
        return;

    if ( b == yy_current_buffer )
        yy_current_buffer = (YY_BUFFER_STATE) 0;

    if ( b->yy_is_our_buffer )
        yy_flex_free( (void *) b->yy_ch_buf );

    yy_flex_free( (void *) b );
}

extern "C" int isatty YY_PROTO(( int ));

void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )
{
    yy_flush_buffer( b );

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

    b->yy_is_interactive = 0;
}

void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    if ( ! b )
        return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.*/
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if( b == yy_current_buffer )
        yy_load_buffer_state();
}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif /* !YY_NO_SCAN_BYTES */


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
{
    if( yy_start_stack_ptr >= yy_start_stack_depth ) {
        yy_size_t new_size;

        yy_start_stack_depth += YY_START_STACK_INCR;
        new_size = yy_start_stack_depth * sizeof(int);

        if( !yy_start_stack )
            yy_start_stack = (int *) yy_flex_alloc( new_size );
        else
            yy_start_stack = (int *) yy_flex_realloc((void *)yy_start_stack, new_size);

        if( !yy_start_stack )
            YY_FATAL_ERROR("out of memory expanding start-condition stack" );
    }
    yy_start_stack[yy_start_stack_ptr++] = YY_START;
    BEGIN(new_state);
}
#endif /* !YY_NO_PUSH_STATE */


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
{
    if( --yy_start_stack_ptr < 0 )
        YY_FATAL_ERROR( "start-condition stack underflow" );
    BEGIN(yy_start_stack[yy_start_stack_ptr]);
}
#endif /* !YY_NO_POP_STATE */


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
{
	if( yy_start_stack_ptr == 0 )
		return YY_START;
    return yy_start_stack[yy_start_stack_ptr - 1];
}
#endif /* !YY_NO_TOP_STATE */

#ifndef YY_EXIT_FAILURE
    #define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError(yyconst char msg[])
{
    cerr << msg << '\n';
    exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */
#undef yyless
#define yyless(n) \
    do {\
        /* Undo effects of setting up yytext. */ \
        yytext[yyleng] = yy_hold_char; \
        yy_c_buf_p = yytext + n; \
        yy_hold_char = *yy_c_buf_p; \
        *yy_c_buf_p = '\0'; \
        yyleng = n; \
    } while ( 0 )


/* Internal utility routines. */
#ifndef yytext_ptr
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
{
    register int i;
    for ( i = 0; i < n; ++i )
        s1[i] = s2[i];
}
#endif /* yytext_ptr */

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen( yyconst char *s )
{
    register int n;
    for( n = 0; s[n]; ++n );

    return n;
}
#endif /* YY_NEED_STRLEN */


static void *yy_flex_alloc( yy_size_t size )
{
    return (void*)malloc( size );
}

static void *yy_flex_realloc( void *ptr, yy_size_t size )
{
/* The cast to (char *) in the following accommodates both
 * implementations that use char* generic pointers, and those
 * that use void* generic pointers.  It works with the latter
 * because both ANSI C and C++ allow castless assignment from
 * any pointer type to void*, and deal with argument conversions
 * as though doing an assignment.*/
    return (void *) realloc( (char *) ptr, size );
}

static void yy_flex_free( void *ptr )
{
    free( ptr );
}

#if YY_MAIN
    int main()
    {
        FlexLexer* lexer = new yyFlexLexer;
        while(lexer->yylex() != 0);
        delete lexer;
        return 0;
    }
#endif
#line 328 "C:\\work\\ape++\\src\\lexers\\LexerXHTML.L"

 /*************************************************************************************/

int CSciLexer<yyFlexLexer>::StateToStyle(int nState) {
	switch(nState) {
		case INITIAL:	return STYLE_TEXT;
		case COMMENT:	return STYLE_COMMENT;
		case STRING:	return STYLE_TAG_STRING;
		case STRING2:	return STYLE_TAG_STRING2;
		case INTAG:		return STYLE_TAG_TEXT;
		case UNDEF:		return STYLE_UNDEF;
		case INTAG_CSS_ATTR: return STYLE_CSS_ATTR;
		case INTAG_CSS_VALUE: return STYLE_CSS_VAL;
// CSS		
		case CSS:			return STYLE_CSS;
		case CSS_SELECTOR:	return STYLE_CSS_SELECTOR;
		case CSS_ATTR:		return STYLE_CSS_ATTR;
		case CSS_VALUE:		return STYLE_CSS_VAL;		
		case CSS_COMMENT:
		case CSS_SL_COMMENT:
		case CSS_SL_COMMENTA:
		case CSS_COMMENTA:	return STYLE_CSS_COMMENT;
		case CSS_STRING:	return STYLE_CSS_STRING;
		case CSS_CHAR:		return STYLE_CSS_CHAR;
// JS		
		case JS:			return STYLE_JS;
		case JS_SLCOMMENT:
		case JS_COMMENT:	return STYLE_JS_COMMENT;
		case JS_STRING:		return STYLE_JS_STRING;
		case JS_CHAR:		return STYLE_JS_CHAR;
		case JS_REGEXP:		return STYLE_JS_REGEXP;
// PHP		
		case PHP:			return STYLE_PHP;
		case PHP_SLCOMMENT:
		case PHP_COMMENT:	return STYLE_PHP_COMMENT;
		case PHP_STRING:	return STYLE_PHP_STRING;
		case PHP_CHAR:		return STYLE_PHP_CHAR;
	}
	return 0;
}