#define yyFlexLexer pascal_FlexLexer
#define yywrap pascal_wrap

#line 5 "C:\\work\\ape++\\src\\lexers\\lexerPascal.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: k:\\backup\\cvsroot/ape/lexer/Lexer.skl,v 1.1 2000/11/15 13:38:44 Basil_Burdo Exp $
 */
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#undef	yywrap

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
    #ifndef __cplusplus
        #define __cplusplus
    #endif
#endif


#ifdef __cplusplus
    #include <stdlib.h>
//  #include <unistd.h>
    class istream;

    /* Use prototypes in function declarations. */
    #define YY_USE_PROTOS
    /* The "const" storage-class-modifier is valid. */
    #define YY_USE_CONST
#else   /* ! __cplusplus */
    #if __STDC__
        #define YY_USE_PROTOS
        #define YY_USE_CONST
    #endif  /* __STDC__ */
#endif  /* ! __cplusplus */

#ifdef YY_USE_CONST
    #define yyconst const
#else
    #define yyconst
#endif

#ifdef YY_USE_PROTOS
    #define YY_PROTO(proto) proto
#else
    #define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.*/
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.*/
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.*/
#define YY_START			((yy_start - 1) / 2)
#define YYSTATE				YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 *  if ( condition_holds )
 *      yyless( 5 );
 *  else
 *      do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        *yy_cp = yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).*/
typedef unsigned int yy_size_t;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
    { \
        if ( ! yy_current_buffer ) \
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
        yy_current_buffer->yy_is_interactive = is_interactive; \
    }

#define yy_set_bol(at_bol) \
    { \
        if ( ! yy_current_buffer ) \
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
        yy_current_buffer->yy_at_bol = at_bol; \
    }

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

/************************************************************************/
/* start of yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init  */
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int CSciLexer<yyFlexLexer>::yylex()
/* end of yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init    */
/************************************************************************/


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
    yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
    yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yy_c_buf_p = yy_cp;

/*********************************************************************************/
/* start of data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 33
#define YY_END_OF_BUFFER 34
static yyconst short int yy_accept[123] =
    {   0,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   34,   32,   30,   31,   32,   21,   21,    4,
       17,   18,   21,   14,   13,   21,   12,   12,   19,   20,
       12,   12,    2,   22,   29,   24,   32,   23,   32,   28,
       32,   27,   32,   30,   31,   15,    3,    1,    0,   14,
       16,    0,   13,    0,    0,   29,   12,   12,   12,   12,
       22,   25,   23,   28,   26,    0,   16,    0,   16,    0,
       12,   12,    0,   12,    0,   11,   11,   11,   12,    0,
       12,    0,   12,    0,   12,    0,    0,    0,    8,   12,
        0,   12,    0,    0,    0,    0,   12,    0,   12,    0,

        0,    0,    0,    0,    0,   12,    0,   12,    0,    0,
        0,   10,   29,    9,   12,    0,    7,    6,    0,    0,
        5,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    1,    1,    6,    5,    5,    7,    8,
        9,   10,   11,    5,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   16,   16,    5,   17,    5,
       18,    5,    5,    5,   19,   19,   19,   20,   21,   22,
       23,   23,   23,   23,   23,   23,   23,   24,   25,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       26,   27,   28,    5,   23,    5,   29,   30,   31,   20,

       32,   33,   23,   23,   34,   35,   23,   36,   23,   37,
       38,   23,   23,   39,   40,   41,   23,   23,   23,   23,
       23,   23,   42,    5,   43,    5,    1,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,

       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    4,    4,    4,    5,    1,    6,    6,
        6,    6,    7,    7,    7,    1,    1,    1,    6,    6,
        6,    6,    6,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    1,    1
    } ;

static yyconst short int yy_base[133] =
    {   0,
        0,    0,   44,    0,   79,   80,   88,   90,   92,   94,
       99,  101,  356,  383,  348,  383,  346,  383,    0,  383,
      338,  383,  331,   94,  113,   98,   97,  124,  383,  383,
      117,   83,  383,  296,    0,  383,  328,  383,  331,  383,
      330,  383,  114,  330,  383,    0,  383,  383,  135,  143,
      151,  162,  170,  112,  294,    0,  106,  132,  150,  166,
      286,  383,  383,  383,  383,  324,  178,  181,  191,  285,
      210,  231,  122,  232,  293,  383,    0,  164,  233,  294,
      237,  284,  273,  287,  176,  288,  274,  311,  383,  255,
      263,  256,  257,  114,  283,  256,  287,  253,  259,  233,

      207,  257,  261,  258,  196,  290,  148,  291,  149,  163,
      292,  383,  154,  383,  302,  153,  383,  312,  145,  318,
      383,  383,  332,  335,  339,  345,  351,  357,  363,  367,
      371,  375
    } ;

static yyconst short int yy_def[133] =
    {   0,
      122,    1,  122,    3,    3,    3,    3,    3,    3,    3,
        3,    3,  122,  122,  122,  122,  122,  122,  123,  122,
      122,  122,  122,  122,  122,  122,  124,  124,  122,  122,
       28,   28,  122,  122,  125,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  123,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  125,   28,   28,   28,   28,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,   28,  122,   28,  122,  122,  125,   28,   28,  122,
       28,  122,   28,  122,   28,  122,  122,  126,  122,   28,
      122,   28,  122,  122,  126,  127,  128,  122,   28,  122,

      129,  122,  122,  127,  129,  130,  122,   28,  122,  131,
      122,  122,  132,  122,  130,  122,  122,  122,  131,  122,
      122,    0,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122
    } ;

static yyconst short int yy_nxt[428] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   18,
       18,   18,   23,   24,   25,   25,   18,   26,   27,   27,
       28,   27,   27,   27,   27,   29,   18,   30,   27,   27,
       31,   28,   27,   27,   27,   27,   27,   32,   27,   27,
       27,   33,   18,   34,   14,   15,   16,   17,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   35,   35,   35,   35,   35,   35,   35,   14,
       14,   14,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   14,   36,   14,   37,   37,
       38,   39,   38,   39,   40,   41,   40,   41,   42,   54,

       42,   40,   41,   40,   41,   49,   57,   50,   50,   51,
       56,   56,   56,   54,   52,   60,   65,   66,   43,   57,
       43,   14,   14,   73,   49,   52,   53,   53,   53,   57,
       14,   55,   14,   52,   14,  101,   14,   56,   56,   56,
       57,   14,   57,   14,   52,   55,  101,   58,   67,   67,
       67,   71,   59,   57,   49,   57,   50,   50,   51,   80,
       58,  114,   49,   52,   51,   51,   51,   73,   57,  117,
      114,   52,   68,   57,   52,   69,   69,   69,   72,  114,
      118,   49,   52,   53,   53,   53,   57,   57,  116,   57,
       52,   67,   67,   67,   69,   69,   69,  105,   52,   57,

       57,   52,   57,   74,   69,   69,   69,   92,  105,   52,
       76,   76,   57,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   77,   77,   77,   76,   76,   78,   78,
       78,   78,   78,   78,   78,   76,   76,   76,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   76,   76,   76,   57,   57,   57,  102,  102,  102,
       57,   81,  111,  109,  103,  103,  103,   57,   57,   57,
       79,   85,   83,   57,   87,   87,   97,  112,   57,   57,
       88,   88,   57,  107,   95,  100,   99,   97,  105,   89,
       89,   57,   57,  111,   98,   57,   57,   90,   94,  108,

       56,   56,   56,  113,  113,  113,  114,  117,  112,   57,
       90,   94,   95,  120,   57,  113,  113,  113,  114,  120,
       93,   91,   86,   84,   82,   75,   65,   57,  121,   61,
       70,   44,   64,   63,  121,   46,   62,   46,   57,   61,
       57,   57,   56,   48,   56,   56,   96,   47,   45,   44,
       96,   96,  104,  104,  104,  122,  104,  104,  106,  122,
      106,  122,  106,  106,  110,  122,  122,  122,  110,  110,
      115,  115,  115,  115,  119,  119,  119,  119,  113,  113,
      113,  113,   13,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,

      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122
    } ;

static yyconst short int yy_chk[428] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    6,
        7,    7,    8,    8,    9,    9,   10,   10,    9,   26,

       10,   11,   11,   12,   12,   24,   32,   24,   24,   24,
       27,   27,   27,   54,   24,   32,   43,   43,    9,   32,
       10,    5,    6,   73,   25,   24,   25,   25,   25,   57,
        7,   26,    8,   25,    9,   94,   10,   28,   28,   28,
       31,   11,   57,   12,   25,   54,   94,   28,   49,   49,
       49,   58,   31,   31,   50,   58,   50,   50,   50,   73,
       28,  119,   51,   50,   51,   51,   51,   60,   58,  116,
      113,   51,   52,   59,   50,   52,   52,   52,   59,  110,
      109,   53,   51,   53,   53,   53,   59,   78,  107,   60,
       53,   67,   67,   67,   68,   68,   68,  105,   67,   85,

       78,   53,   60,   60,   69,   69,   69,   85,  101,   67,
       71,   71,   85,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   72,   74,   79,   96,  102,  104,
       81,   74,  103,  100,   96,  102,  104,   72,   74,   79,
       72,   81,   79,   81,   83,   87,   90,  103,   90,   92,
       83,   87,   99,   98,   95,   93,   92,   90,   97,   83,
       87,   90,   92,  111,   91,   99,   83,   83,   87,   99,

       97,   97,   97,  106,  106,  106,  106,  108,  111,   83,
       83,   87,   88,  118,  108,  115,  115,  115,  115,  120,
       86,   84,   82,   80,   75,   70,   66,  108,  118,   61,
       55,   44,   41,   39,  120,  123,   37,  123,  124,   34,
      124,  124,  125,   23,  125,  125,  126,   21,   17,   15,
      126,  126,  127,  127,  127,   13,  127,  127,  128,    0,
      128,    0,  128,  128,  129,    0,    0,    0,  129,  129,
      130,  130,  130,  130,  131,  131,  131,  131,  132,  132,
      132,  132,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,

      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
#define INITIAL 0
#line 2 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
#include "LexBase.h"
#define COMMENT 1
#define COMMENT2 2
#define SLCOMMENT 3
#define STRING 4
#define CHAR 5

// without - "'	esc []-\/   !
#line 25 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"

bool isPascalKeyword( const char* text, bool& bInc, bool& bDec ) 
{
	if( !strcmpi(text,"class") || !strcmpi(text,"object") || !strcmpi(text,"dispinterface") || 
		!strcmpi(text,"record") || !strcmpi(text,"try") || !strcmpi(text,"case") || !strcmpi(text,"begin") ||
		!strcmpi(text,"interface") )
		bInc = true;
	if( !strcmpi(text,"end") )
		bDec = true;
	if( !strcmpi(text,"finally") || !strcmpi(text,"except") || !strcmpi(text,"implementation") ) {
		bDec = true;
		bInc = true;
	}
	static CKeywordsIC kwPascal("TXT_PASCAL_KW");
	return kwPascal.is(text);
}

#define STYLE_TEXT			0
#define STYLE_KW			1
#define STYLE_COMMENT		2
#define STYLE_SYMBOL		3
#define STYLE_STRING		4
#define STYLE_CHAR			5
#define STYLE_NUMBER		6
#define STYLE_UNQ			8

#line 446 "C:\\work\\ape++\\src\\lexers\\lexerPascal.cpp"
/* end of data tables for the DFA and the user's section 1 definitions go here   */
/*********************************************************************************/


#ifndef yytext_ptr
    static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
    static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
    static int yy_start_stack_ptr = 0;
    static int yy_start_stack_depth = 0;
    static int *yy_start_stack = 0;
    #ifndef YY_NO_PUSH_STATE
        static void yy_push_state YY_PROTO(( int new_state ));
    #endif
    #ifndef YY_NO_POP_STATE
        static void yy_pop_state YY_PROTO(( void ));
    #endif
    #ifndef YY_NO_TOP_STATE
        static int yy_top_state YY_PROTO(( void ));
    #endif
#else
    #define YY_NO_PUSH_STATE    1
    #define YY_NO_POP_STATE     1
    #define YY_NO_TOP_STATE     1
#endif

#ifdef YY_MALLOC_DECL
    YY_MALLOC_DECL
#else
    #if __STDC__
        #ifndef __cplusplus
            #include <stdlib.h>
        #endif
    #else
        /* Just try to get by without declaring the routines.  This will fail
         * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
         * or sizeof(void*) != sizeof(int).
         */
    #endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
    #define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
    #define ECHO LexerOutput( yytext, yyleng )
#endif /* !ECHO */

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
    #define YY_INPUT(buf,result,max_size) \
        if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
            YY_FATAL_ERROR( "input in flex scanner failed" );
#endif /* !YY_INPUT */

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.*/
#ifndef yyterminate
    #define yyterminate() return YY_NULL
#endif /* !yyterminate */

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
    #define YY_START_STACK_INCR 25
#endif /* !YY_START_STACK_INCR */

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
    #define YY_FATAL_ERROR(msg) LexerError( msg )
#endif /* !YY_FATAL_ERROR */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
    #define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.*/
#ifndef YY_USER_ACTION
    #define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
    #define YY_BREAK    break;
#endif

/************************************************************************/
/* start of YY_RULE_SETUP definition                                    */
#define YY_RULE_SETUP \
	YY_USER_ACTION
/* end of YY_RULE_SETUP definition                                      */
/************************************************************************/

YY_DECL
{
    register yy_state_type yy_current_state;
    register char *yy_cp, *yy_bp;
    register int yy_act;

/************************************************************************/
/* start of user's declarations                                         */
#line 53 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"

 /*************************************************************************************/

#line 570 "C:\\work\\ape++\\src\\lexers\\lexerPascal.cpp"
/* end of user's declarations                                           */
/************************************************************************/

    if( yy_init ) {
        yy_init = 0;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif /* YY_USER_INIT */

        if( !yy_start )
            yy_start = 1;   /* first start state */

        if( !yyin )
            yyin = &cin;

        if( !yyout )
            yyout = &cout;

        if( !yy_current_buffer )
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

        yy_load_buffer_state();
    }

    while( 1 )      /* loops until end-of-file is reached */
    {
/************************************************************************/
/* start of yymore()-related code                                       */
/* end of yymore()-related code                                         */
/************************************************************************/
        
        yy_cp = yy_c_buf_p;

        *yy_cp = yy_hold_char; /* Support of yytext. */

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run. */
        yy_bp = yy_cp;

/************************************************************************/
/* start of code to set up and find next match                          */
		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 123 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 383 );
/* end of code to set up and find next match                            */
/************************************************************************/

yy_find_action:

/************************************************************************/
/* start of code to find the action number                              */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}
/* end of code to find the action number                                */
/************************************************************************/

        YY_DO_BEFORE_ACTION;

/************************************************************************/
/* start of code for yylineno update                                    */
/* end if code for yylineno update                                      */
/************************************************************************/

do_action:  /* This label is used only to access EOF actions. */

/************************************************************************/
/* start of debug code                                                  */
/* end of debug code                                                    */
/************************************************************************/
        switch ( yy_act ) { /* beginning of action switch */
/************************************************************************/
/* start of actions code                                                */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;


case 1:
YY_RULE_SETUP
#line 57 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
BEGIN(SLCOMMENT); SetStyle();
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
BEGIN(COMMENT); SetStyle(); levelIncrease();
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 59 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
BEGIN(COMMENT2); SetStyle(); levelIncrease();
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
BEGIN(STRING);	  SetStyle();
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 62 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
{
						char* pText;
						for( pText=yytext; *pText!='i'; pText++ );
						int len = (pText-yytext);
						SetStyle( MatchStart(), MatchStart()+1, STYLE_SYMBOL );
						SetStyle( MatchStart()+1, MatchStart()+len, STYLE_TEXT );
						SetStyle( MatchStart()+len, MatchStart()+len+9, STYLE_KW );
						SetStyle( MatchStart()+len+9, MatchEnd()-1, STYLE_TEXT );
						SetStyle( MatchEnd()-1, MatchEnd(), STYLE_SYMBOL );
						}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 73 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
{
						char* pText;
						for( pText=yytext; *pText!='i'; pText++ );
						int len = (pText-yytext);
						SetStyle( MatchStart(), MatchStart()+1, STYLE_SYMBOL );
						SetStyle( MatchStart()+1, MatchStart()+len, STYLE_TEXT );
						SetStyle( MatchStart()+len, MatchEnd(), STYLE_KW );
						levelIncrease();
						}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 83 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
{ // sample : procedure ... of object;
						SetStyle( MatchStart(), MatchEnd()-1, STYLE_KW ); 
						SetStyle( MatchEnd()-1, MatchEnd(), STYLE_SYMBOL );
						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
{
						SetStyle( MatchStart(), MatchStart()+5, STYLE_KW );
						SetStyle( MatchStart()+5, MatchEnd()-1, STYLE_TEXT );
						SetStyle( MatchEnd()-1, MatchEnd(), STYLE_SYMBOL );
						}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 94 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
{
						SetStyle( MatchStart(), MatchStart()+8, STYLE_KW ); // class of
						SetStyle( MatchStart()+8, MatchEnd()-1, STYLE_TEXT ); // IDENT
						SetStyle( MatchEnd()-1, MatchEnd(), STYLE_SYMBOL );
						}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 100 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
{
						SetStyle( MatchStart(), MatchStart()+5, STYLE_KW );
						char* pText=yytext+5;
						for( ; *pText; pText++ ) {
							int p = MatchStart()+pText-yytext;
							SetStyle( p, p+1, (*pText=='(' || *pText==')') ? STYLE_SYMBOL : STYLE_TEXT );
						}
						SetStyle( MatchEnd()-1, MatchEnd(), STYLE_SYMBOL );
						}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 110 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
{
						SetStyle( MatchStart(), MatchEnd()-1, STYLE_KW );
						SetStyle( MatchEnd()-1, MatchEnd(), STYLE_SYMBOL );
						levelDecrease();
						}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 116 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
{
						bool bInc=false, bDec=false;
						if( isPascalKeyword(yytext,bInc,bDec) ) SetStyle(STYLE_KW); else SetStyle();
						if( bDec ) levelDecrease();
						if( bInc ) levelIncrease();
						}
	YY_BREAK
/* numbers */
case 13:
#line 125 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
case 14:
#line 126 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
case 15:
#line 127 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
case 16:
YY_RULE_SETUP
#line 127 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle(STYLE_NUMBER);
	YY_BREAK
/* folding */
case 17:
YY_RULE_SETUP
#line 130 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle(STYLE_SYMBOL);	levelIncrease();
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 131 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle(STYLE_SYMBOL);	levelDecrease();
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 132 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle(STYLE_SYMBOL);	levelIncrease();
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 133 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle(STYLE_SYMBOL);	levelDecrease();
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 135 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle(STYLE_SYMBOL);
	YY_BREAK
/* invalid chars - all second part of the ASCII table */
case 22:
YY_RULE_SETUP
#line 138 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle(IStyler::styleInvalidText);
	YY_BREAK


case 23:
YY_RULE_SETUP
#line 142 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
BEGIN(INITIAL); SetStyle(); 
	YY_BREAK


case 24:
YY_RULE_SETUP
#line 145 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle();	BEGIN(INITIAL); levelDecrease();
	YY_BREAK


case 25:
YY_RULE_SETUP
#line 148 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle();	BEGIN(INITIAL); levelDecrease();
	YY_BREAK


case 26:
YY_RULE_SETUP
#line 152 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle();
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 153 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle(); BEGIN(INITIAL);
	YY_BREAK


/*invalid end-of-line*/
case 28:
YY_RULE_SETUP
#line 158 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle(STYLE_UNQ); BEGIN(INITIAL);
	YY_BREAK


case 29:
#line 163 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
case 30:
#line 164 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
case 31:
#line 165 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
case 32:
YY_RULE_SETUP
#line 165 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
SetStyle();
	YY_BREAK

case 33:
YY_RULE_SETUP
#line 168 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"
ECHO;
	YY_BREAK
#line 883 "C:\\work\\ape++\\src\\lexers\\lexerPascal.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(COMMENT2):
case YY_STATE_EOF(SLCOMMENT):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHAR):
	yyterminate();
/* end of actions code                                                  */
/************************************************************************/
        case YY_END_OF_BUFFER: {
            /* Amount of text matched not including the EOB char. */
            int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;
    
            /* Undo the effects of YY_DO_BEFORE_ACTION. */
            *yy_cp = yy_hold_char;
            YY_RESTORE_YY_MORE_OFFSET

            if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
            {/* We're scanning a new file or input source.  It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex().  If so, then we have to assure
             * consistency between yy_current_buffer and our
             * globals.  Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.*/
                yy_n_chars = yy_current_buffer->yy_n_chars;
                yy_current_buffer->yy_input_file = yyin;
                yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
            }

            /* Note that here we test for yy_c_buf_p "<=" to the position
             * of the first EOB in the buffer, since yy_c_buf_p will
             * already have been incremented past the NUL character
             * (since all states make transitions on EOB to the
             * end-of-buffer state).  Contrast this with the test
             * in input().*/
            if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            {/* This was really a NUL. */
                yy_state_type yy_next_state;

                yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state();

            /* Okay, we're now positioned to make the NUL
             * transition.  We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).*/

                yy_next_state = yy_try_NUL_trans( yy_current_state );

                yy_bp = yytext_ptr + YY_MORE_ADJ;

                if( yy_next_state )
                {/* Consume the NUL. */
                    yy_cp = ++yy_c_buf_p;
                    yy_current_state = yy_next_state;
                    goto yy_match;
                } else {
/************************************************************************/
/* start ofcode to do back-up for compressed tables and set up yy_cp    */              
				yy_cp = yy_c_buf_p;
/* end if code to do back-up for compressed tables and set up yy_cp     */              
/************************************************************************/
                    goto yy_find_action;
                }
            } else
            switch ( yy_get_next_buffer() ) {
            case EOB_ACT_END_OF_FILE: {
                yy_did_buffer_switch_on_eof = 0;
                if( yywrap() ) {
                /* Note: because we've taken care in
                 * yy_get_next_buffer() to have set up
                 * yytext, we can now set up
                 * yy_c_buf_p so that if some total
                 * hoser (like flex itself) wants to
                 * call the scanner after we return the
                 * YY_NULL, it'll still work - another
                 * YY_NULL will get returned.*/
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
                    yy_act = YY_STATE_EOF(YY_START);
                    goto do_action;
                } else {
                    if( !yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
                }
                break;}
            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;
                yy_current_state = yy_get_previous_state();
                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_match;
            case EOB_ACT_LAST_MATCH:
                yy_c_buf_p = &yy_current_buffer->yy_ch_buf[yy_n_chars];
                yy_current_state = yy_get_previous_state();
                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_find_action;
            }
            break;}
        default:
            YY_FATAL_ERROR("fatal flex scanner internal error--no action found" );
        } /* end of action switch */
    } /* end of scanning one token */
} /* end of yylex */
#undef YY_DECL

yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
    yyin            = arg_yyin;
    yyout           = arg_yyout;
    yy_c_buf_p      = 0;
    yy_init         = 1;
    yy_start        = 0;
    yy_flex_debug   = 0;
    yylineno        = 1;    // this will only get updated if %option yylineno

    yy_did_buffer_switch_on_eof					= 0;

    yy_looking_for_trail_begin                  = 0;
    yy_more_flag                                = 0;
    yy_more_len                                 = 0;
    yy_more_offset = yy_prev_more_offset        = 0;

    yy_start_stack_ptr = yy_start_stack_depth   = 0;
    yy_start_stack                              = 0;

    yy_current_buffer                           = 0;

#ifdef YY_USES_REJECT
    yy_state_buf                                = new yy_state_type[YY_BUF_SIZE + 2];
#else
    yy_state_buf                                = 0;
#endif
}

yyFlexLexer::~yyFlexLexer()
{
    delete yy_state_buf;
    yy_delete_buffer( yy_current_buffer );
}

void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
    if ( new_in ) {
        yy_delete_buffer( yy_current_buffer );
        yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
    }

    if ( new_out )
        yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif /* !YY_INTERACTIVE */
{
    if( yyin->eof() || yyin->fail() )
        return 0;

#ifdef YY_INTERACTIVE
    yyin->get( buf[0] );
    if( yyin->eof() )
        return 0;
    if( yyin->bad() )
        return -1;
    return 1;
#else  /* YY_INTERACTIVE */
    (void) yyin->read( buf, max_size );
    if( yyin->bad() )
        return -1;
    else
        return yyin->gcount();
#endif /* !YY_INTERACTIVE */
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
    (void) yyout->write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *  EOB_ACT_LAST_MATCH -
 *  EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *  EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    register char *dest = yy_current_buffer->yy_ch_buf;
    register char *source = yytext_ptr;
    register int number_to_move, i;
    int ret_val;

    if( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
        YY_FATAL_ERROR("fatal flex scanner internal error--end of buffer missed" );

    if( yy_current_buffer->yy_fill_buffer == 0 )
    { /* Don't try to fill the buffer, so this is an EOF. */
        if( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 ) {
        /* We matched a single character, the EOB, so
         *  treat this as a final EOF.
         */
            return EOB_ACT_END_OF_FILE;
        } else {
        /* We matched some text prior to the EOB, first
         * process it.
         */
            return EOB_ACT_LAST_MATCH;
        }
    }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

    for( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

    if( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
    /* don't do the read, it's not guaranteed to return an EOF,
     * just force an EOF
     */
        yy_current_buffer->yy_n_chars = yy_n_chars = 0;

    else {
        int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;
        while ( num_to_read <= 0 ) {
            /* Not enough room in the buffer - grow it. */
        #ifdef YY_USES_REJECT
            YY_FATAL_ERROR("input buffer overflow, can't enlarge buffer because scanner uses REJECT");
        #else
            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = yy_current_buffer;

            int yy_c_buf_p_offset = (int)(yy_c_buf_p - b->yy_ch_buf);

            if( b->yy_is_our_buffer ) {
                int new_size = b->yy_buf_size * 2;
                if ( new_size <= 0 )
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char *)
                    /* Include room in for 2 EOB chars. */
                    yy_flex_realloc( (void *) b->yy_ch_buf, b->yy_buf_size + 2 );
            } else /* Can't grow it, we don't own it. */
                b->yy_ch_buf = 0;

            if ( ! b->yy_ch_buf )
                YY_FATAL_ERROR("fatal error - scanner input buffer overflow" );

            yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];
            num_to_read = yy_current_buffer->yy_buf_size -
                        number_to_move - 1;
        #endif
        }

        if( num_to_read > YY_READ_BUF_SIZE )
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]), yy_n_chars, num_to_read );
        yy_current_buffer->yy_n_chars = yy_n_chars;
    }

    if( yy_n_chars == 0 ) {
        if( number_to_move == YY_MORE_ADJ ) {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart( yyin );
        } else {
            ret_val = EOB_ACT_LAST_MATCH;
            yy_current_buffer->yy_buffer_status = YY_BUFFER_EOF_PENDING;
        }
    } else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

    return ret_val;
}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
{
    register yy_state_type yy_current_state;
    register char *yy_cp;
/*********************************************************************/
/* start of code to get the start state into yy_current_state        */
	yy_current_state = yy_start;
/* end of start of code to get the start state into yy_current_state */
/*********************************************************************/

    for( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
    {
/*********************************************************************/
/* start of code to find the next state                              */     
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 123 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
/* end of code to find the next state                                */     
/*********************************************************************/
    }

    return yy_current_state;
}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *  next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
    register int yy_is_jam;
/*********************************************************************/
/* start of code to find the next state, and perhaps do backing up   */
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 123 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 122);
/* end ofcode to find the next state, and perhaps do backing up      */
/*********************************************************************/
    return yy_is_jam ? 0 : yy_current_state;
}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
{
    register char *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if( yy_cp < yy_current_buffer->yy_ch_buf + 2 ) {
    /* need to shift things up to make room */
    /* +2 for EOB chars. */
        register int number_to_move = yy_n_chars + 2;
        register char *dest = &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
        register char *source = &yy_current_buffer->yy_ch_buf[number_to_move];

        while( source > yy_current_buffer->yy_ch_buf )
            *--dest = *--source;

        yy_cp += (int) (dest - source);
        yy_bp += (int) (dest - source);
        yy_current_buffer->yy_n_chars = yy_n_chars = yy_current_buffer->yy_buf_size;

        if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
            YY_FATAL_ERROR( "flex scanner push-back overflow" );
    }
    *--yy_cp = (char) c;

/****************************/
/* start of update yylineno */
/* end of update yylineno   */
/****************************/

    yytext_ptr = yy_bp;
    yy_hold_char = *yy_cp;
    yy_c_buf_p = yy_cp;
}


int yyFlexLexer::yyinput()
{
    int c;
    *yy_c_buf_p = yy_hold_char;

    if( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR ) {
    /* yy_c_buf_p now points to the character we want to return.
     * If this occurs *before* the EOB characters, then it's a
     * valid NUL; if not, then we've hit the end of the buffer.
     */
        if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
        /* This was really a NUL. */
            *yy_c_buf_p = '\0';

        else {
        /* need more input */
            int offset = yy_c_buf_p - yytext_ptr;
            ++yy_c_buf_p;

            switch ( yy_get_next_buffer() ) {
            case EOB_ACT_LAST_MATCH:
                /* This happens because yy_g_n_b()
                 * sees that we've accumulated a
                 * token and flags that we need to
                 * try matching the token before
                 * proceeding.  But for input(),
                 * there's no matching to consider.
                 * So convert the EOB_ACT_LAST_MATCH
                 * to EOB_ACT_END_OF_FILE.*/

                /* Reset buffer status. */
                yyrestart( yyin );

                /* fall through */

            case EOB_ACT_END_OF_FILE:
                {
                    if ( yywrap() )
                        return EOF;

                    if ( ! yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;                    
                        
                #ifdef __cplusplus
                    return yyinput();
                #else
                    return input();
                #endif
                }

            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p = yytext_ptr + offset;
                break;
            }
        }
    }

    c = *(unsigned char *) yy_c_buf_p;  /* cast for 8-bit char's */
    *yy_c_buf_p = '\0'; /* preserve yytext */
    yy_hold_char = *++yy_c_buf_p;

/************************************/
/* start of update BOL and yylineno */
/* end of update BOL and yylineno   */
/************************************/

    return c;
}

void yyFlexLexer::yyrestart( std::istream* input_file )
{
    if ( ! yy_current_buffer )
        yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    if( yy_current_buffer == new_buffer )
        return;

    if( yy_current_buffer ) {
    /* Flush out information for old buffer. */
        *yy_c_buf_p = yy_hold_char;
        yy_current_buffer->yy_buf_pos = yy_c_buf_p;
        yy_current_buffer->yy_n_chars = yy_n_chars;
    }

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
}

void yyFlexLexer::yy_load_buffer_state()
{
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
}

YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
    if( ! b ) YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
    if( ! b->yy_ch_buf ) YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_is_our_buffer = 1;

    yy_init_buffer( b, file );

    return b;
}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    if ( ! b )
        return;

    if ( b == yy_current_buffer )
        yy_current_buffer = (YY_BUFFER_STATE) 0;

    if ( b->yy_is_our_buffer )
        yy_flex_free( (void *) b->yy_ch_buf );

    yy_flex_free( (void *) b );
}

extern "C" int isatty YY_PROTO(( int ));

void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )
{
    yy_flush_buffer( b );

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

    b->yy_is_interactive = 0;
}

void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    if ( ! b )
        return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.*/
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if( b == yy_current_buffer )
        yy_load_buffer_state();
}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif /* !YY_NO_SCAN_BYTES */


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
{
    if( yy_start_stack_ptr >= yy_start_stack_depth ) {
        yy_size_t new_size;

        yy_start_stack_depth += YY_START_STACK_INCR;
        new_size = yy_start_stack_depth * sizeof(int);

        if( !yy_start_stack )
            yy_start_stack = (int *) yy_flex_alloc( new_size );
        else
            yy_start_stack = (int *) yy_flex_realloc((void *)yy_start_stack, new_size);

        if( !yy_start_stack )
            YY_FATAL_ERROR("out of memory expanding start-condition stack" );
    }
    yy_start_stack[yy_start_stack_ptr++] = YY_START;
    BEGIN(new_state);
}
#endif /* !YY_NO_PUSH_STATE */


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
{
    if( --yy_start_stack_ptr < 0 )
        YY_FATAL_ERROR( "start-condition stack underflow" );
    BEGIN(yy_start_stack[yy_start_stack_ptr]);
}
#endif /* !YY_NO_POP_STATE */


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
{
	if( yy_start_stack_ptr == 0 )
		return YY_START;
    return yy_start_stack[yy_start_stack_ptr - 1];
}
#endif /* !YY_NO_TOP_STATE */

#ifndef YY_EXIT_FAILURE
    #define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError(yyconst char msg[])
{
    cerr << msg << '\n';
    exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */
#undef yyless
#define yyless(n) \
    do {\
        /* Undo effects of setting up yytext. */ \
        yytext[yyleng] = yy_hold_char; \
        yy_c_buf_p = yytext + n; \
        yy_hold_char = *yy_c_buf_p; \
        *yy_c_buf_p = '\0'; \
        yyleng = n; \
    } while ( 0 )


/* Internal utility routines. */
#ifndef yytext_ptr
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
{
    register int i;
    for ( i = 0; i < n; ++i )
        s1[i] = s2[i];
}
#endif /* yytext_ptr */

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen( yyconst char *s )
{
    register int n;
    for( n = 0; s[n]; ++n );

    return n;
}
#endif /* YY_NEED_STRLEN */


static void *yy_flex_alloc( yy_size_t size )
{
    return (void*)malloc( size );
}

static void *yy_flex_realloc( void *ptr, yy_size_t size )
{
/* The cast to (char *) in the following accommodates both
 * implementations that use char* generic pointers, and those
 * that use void* generic pointers.  It works with the latter
 * because both ANSI C and C++ allow castless assignment from
 * any pointer type to void*, and deal with argument conversions
 * as though doing an assignment.*/
    return (void *) realloc( (char *) ptr, size );
}

static void yy_flex_free( void *ptr )
{
    free( ptr );
}

#if YY_MAIN
    int main()
    {
        FlexLexer* lexer = new yyFlexLexer;
        while(lexer->yylex() != 0);
        delete lexer;
        return 0;
    }
#endif
#line 168 "C:\\work\\ape++\\src\\lexers\\lexerPascal.L"

/*************************************************************************************/

int CSciLexer<yyFlexLexer>::StateToStyle(int nState) {
	switch(nState) {
		case INITIAL:		return STYLE_TEXT;
		case SLCOMMENT:
		case COMMENT2:
		case COMMENT:		return STYLE_COMMENT;
		case STRING:		return STYLE_STRING;
		case CHAR:			return STYLE_CHAR;
	}
	return 0;
}